/* Generated by scripts/build-messages.mjs from the catalogues in messages/. Do not edit — run `yarn messages`. */

/**
 * How many messages a language has not been written in yet.
 *
 * Those render in the source language rather than as keys, which is
 * readable and also invisible — so the number is here, and the language
 * section in settings says it beside the language it belongs to. Zero is a
 * language somebody has finished.
 */
import type { Locale } from './locales.js';

const UNTRANSLATED: Record<Locale, number> = {
	en: 0,
	'pt-BR': 100,
	de: 100,
	es: 100
};

export function untranslatedCount(locale: Locale): number {
	return UNTRANSLATED[locale] ?? 0;
}
