/* Generated by scripts/build-messages.mjs from messages/en.json. Do not edit — run `yarn messages`. */

/** Every message this app has. A key not in here does not exist. */
export type MessageKey =
	| 'settings.language.heading'
	| 'settings.language.hint'
	| 'settings.language.saved'
	| 'settings.language.untranslated';

/**
 * The keys that take values, and which values.
 *
 * Read out of the placeholders in the source catalogue, so a message that
 * gains a `{name}` makes every call site that does not pass one a type error
 * rather than a sentence with a brace in it.
 */
export interface MessageValuesFor {
	'settings.language.untranslated': { count: number };
}

/** A message that takes values — it may not be called without them. */
export type KeyWithValues = keyof MessageValuesFor;

/** A message that takes none. */
export type PlainKey = Exclude<MessageKey, KeyWithValues>;
