/* Generated by scripts/build-messages.mjs from the list of languages in locales.ts. Do not edit — run `yarn messages`. */

/**
 * One language, fetched when it is the one being read.
 *
 * Written out as a switch rather than built from the locale, because a
 * bundler can only split what it can see: an import with a variable in it
 * either fails or drags every language into one chunk.
 */
import type { Catalogue } from './index.js';
import type { Locale } from './locales.js';

export async function loadCatalogue(locale: Locale): Promise<Catalogue> {
	switch (locale) {
		case 'pt-BR':
			return (await import('./catalogues/pt-BR.js')).messages;
		default:
			return (await import('./catalogues/en.js')).messages;
	}
}
