/* Generated by scripts/build-messages.mjs from the list of languages in locales.ts. Do not edit — run `yarn messages`. */

/**
 * One language, fetched when it is the one being read.
 *
 * Written out as a switch rather than built from the locale, because a
 * bundler can only split what it can see: an import with a variable in it
 * either fails or drags every language into one chunk.
 */
import type { Catalogue } from './core.js';
import type { Locale } from './locales.js';

export async function loadCatalogue(locale: Locale): Promise<Catalogue> {
	switch (locale) {
		case 'pt-BR':
			return (await import('./catalogues/pt-BR.js')).messages;
		case 'de':
			return (await import('./catalogues/de.js')).messages;
		case 'es':
			return (await import('./catalogues/es.js')).messages;
		default:
			return (await import('./catalogues/en.js')).messages;
	}
}

/**
 * Which of them are still the source language, for a build that marks them.
 *
 * A separate module from the catalogue so production never fetches it: the
 * only caller is the dev and staging shell.
 */
export async function loadBorrowed(locale: Locale): Promise<ReadonlySet<string>> {
	switch (locale) {
		case 'pt-BR':
			return (await import('./borrowed/pt-BR.js')).borrowed;
		case 'de':
			return (await import('./borrowed/de.js')).borrowed;
		case 'es':
			return (await import('./borrowed/es.js')).borrowed;
		default:
			return new Set();
	}
}
