/* Generated by scripts/build-messages.mjs from messages/pt-BR.json. Do not edit — run `yarn messages`. */

import type { Catalogue } from '../index.js';

export const messages: Catalogue = {
	'settings.language.heading': 'Idioma',
	'settings.language.hint':
		'Em que idioma esta conta lê o aplicativo. Os e-mails enviados a você seguem a mesma escolha.',
	'settings.language.saved': 'Salvo.',
	'settings.language.untranslated': {
		one: '{count} mensagem ainda não foi escrita neste idioma e aparece em inglês.',
		other: '{count} mensagens ainda não foram escritas neste idioma e aparecem em inglês.'
	}
};
