/* Generated by scripts/build-messages.mjs from messages/de.json. Do not edit — run `yarn messages`. */

/**
 * The messages this language has not been written in yet.
 *
 * Fetched only by a dev or staging build, which paints them red so a
 * screen says what is still English without anybody comparing it against
 * a list. Production never asks for this module, so it is never in the
 * bundle a reader downloads.
 */
export const borrowed: ReadonlySet<string> = new Set([
	'tour.aNameOrTheMoment',
	'tour.hearItBeforeYouKeep',
	'tour.leaveTheNameAloneAnd',
	'tour.playItBackAndScrub',
	'tour.pressRecordAndTalk',
	'tour.recordings',
	'tour.sayItInsteadOfTyping'
]);
