/**
 * The wiki, built from the code rather than written beside it.
 *
 * A hand-written page is true on the day it is written and quietly stops being
 * true afterwards, which is worse than no page at all because people trust it.
 * So every page here is derived from something the app actually enforces:
 *
 *   Data model     drizzle/meta/<latest>_snapshot.json — produced by
 *                  `yarn db:generate` from the schema, so it cannot disagree
 *                  with the tables that exist.
 *   HTTP API       the route files themselves, read as a syntax tree: the
 *                  methods they export and the scope each one demands, taken
 *                  from the `authenticateApi(event, '…')` call rather than
 *                  from a list somebody maintains.
 *   Scopes         the SCOPES object in services/tokens.ts.
 *   Services       each module's own header comment and its exported
 *                  signatures. The prose in this app already lives next to
 *                  the code and moves with it; this only collects it.
 *   Keyboard       PAGE_SHORTCUTS, the same table the app binds and the help
 *                  sheet renders.
 *
 * Anything that cannot be derived is not generated. A page that has to be
 * remembered is the thing this exists to avoid.
 *
 *   node scripts/build-docs.mjs           write docs/wiki/
 *   node scripts/build-docs.mjs --check   fail if what is on disk is stale
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import * as prettier from 'prettier';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs', 'wiki');
const CHECK = process.argv.includes('--check');

const STAMP = '<!-- Generated by scripts/build-docs.mjs. Do not edit: run `yarn docs`. -->\n\n';

/* ------------------------------------------------------------------ helpers */

function walk(dir, match, found = []) {
	if (!existsSync(dir)) return found;
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) walk(full, match, found);
		else if (match(entry.name)) found.push(full);
	}
	return found;
}

function parse(file) {
	return ts.createSourceFile(
		file,
		readFileSync(file, 'utf8'),
		ts.ScriptTarget.Latest,
		true,
		ts.ScriptKind.TS
	);
}

/** Strip the stars off a `/** … *\/` block and give back the prose inside. */
function undecorate(raw) {
	return raw
		.replace(/^\/\*\*/, '')
		.replace(/\*\/$/, '')
		.split('\n')
		.map((l) => l.replace(/^\s*\* ?/, '').trimEnd())
		.join('\n')
		.trim();
}

/**
 * The file's own header comment.
 *
 * By convention here it is the first `/** … *\/` in the file, which in most
 * modules sits *below* the imports — so it cannot be found by asking the first
 * statement what its leading comment is. Doing that attributed the header to
 * whichever declaration happened to follow it, and then handed that
 * declaration's own comment back as the module summary.
 */
function moduleDocOf(source) {
	const text = source.getFullText();
	const start = text.indexOf('/**');
	if (start === -1) return '';
	const end = text.indexOf('*/', start);
	if (end === -1) return '';
	return undecorate(text.slice(start, end + 2));
}

/**
 * The comment block above a node, as prose.
 *
 * Only `/** … *\/` blocks: a `//` note is a remark to the next person editing
 * the line, and pulling those into a manual produces a page of asides. The
 * file header is excluded — it belongs to the module, and the statement that
 * happens to follow it must not claim it.
 */
function docOf(node, source, moduleDoc = '') {
	const ranges = ts.getLeadingCommentRanges(source.getFullText(), node.getFullStart()) ?? [];
	const blocks = ranges.filter((r) => source.getFullText().slice(r.pos, r.pos + 3) === '/**');
	if (!blocks.length) return '';

	const doc = undecorate(source.getFullText().slice(blocks.at(-1).pos, blocks.at(-1).end));
	return doc === moduleDoc ? '' : doc;
}

/** The first paragraph of a doc block — the sentence that says what a thing is. */
function summary(doc) {
	return doc.split('\n\n')[0].replace(/\n/g, ' ').trim();
}

/* -------------------------------------------------------------- data model */

function latestSnapshot() {
	const dir = join(ROOT, 'drizzle', 'meta');
	const snapshots = readdirSync(dir)
		.filter((f) => f.endsWith('_snapshot.json'))
		.sort();
	return JSON.parse(readFileSync(join(dir, snapshots.at(-1)), 'utf8'));
}

function dataModelPage() {
	const snapshot = latestSnapshot();
	const tables = Object.values(snapshot.tables).sort((a, b) => a.name.localeCompare(b.name));

	const out = [
		STAMP,
		'# Data model\n',
		`Every table the database has, from the migration snapshot \`drizzle-kit\` writes`,
		`out of the schema — so this page cannot disagree with the schema, and a`,
		`column added without a migration does not appear here because it does not`,
		`exist.\n`,
		`**${tables.length} tables.**\n`,
		'| Table | Columns | Belongs to a user |',
		'| --- | --- | --- |'
	];

	const ownsUser = (t) => Object.keys(t.columns).includes('user_id');
	for (const t of tables) {
		out.push(
			`| [\`${t.name}\`](#${t.name.replace(/_/g, '')}) | ${Object.keys(t.columns).length} | ${ownsUser(t) ? 'yes' : '—'} |`
		);
	}
	out.push('');

	for (const t of tables) {
		out.push(`## ${t.name}\n`);

		out.push('| Column | Type | Null | Default | Notes |');
		out.push('| --- | --- | --- | --- | --- |');

		const fks = Object.values(t.foreignKeys ?? {});
		for (const c of Object.values(t.columns)) {
			const notes = [];
			if (c.primaryKey) notes.push('primary key');
			if (c.autoincrement) notes.push('auto');
			const fk = fks.find((f) => (f.columnsFrom ?? []).includes(c.name));
			if (fk) notes.push(`→ \`${fk.tableTo}.${(fk.columnsTo ?? []).join(', ')}\``);

			out.push(
				`| \`${c.name}\` | ${c.type} | ${c.notNull ? 'not null' : 'null'} | ${
					c.default === undefined ? '—' : `\`${String(c.default)}\``
				} | ${notes.join(', ') || '—'} |`
			);
		}
		out.push('');

		const indexes = Object.values(t.indexes ?? {});
		if (indexes.length) {
			out.push('Indexes:\n');
			for (const i of indexes) {
				out.push(
					`- \`${i.name}\` on ${i.columns.map((c) => `\`${c}\``).join(', ')}${i.isUnique ? ' — unique' : ''}`
				);
			}
			out.push('');
		}

		const checks = Object.values(t.checkConstraints ?? {});
		if (checks.length) {
			out.push('Checks — enforced by the database, not only by the service layer:\n');
			for (const c of checks) out.push(`- \`${c.name}\`: \`${c.value}\``);
			out.push('');
		}
	}

	return out.join('\n');
}

/* -------------------------------------------------------------------- API */

/** The scope a handler demands, from its own `authenticateApi` call. */
function scopeIn(node, source) {
	let scope = null;
	const visit = (n) => {
		if (
			ts.isCallExpression(n) &&
			n.expression.getText(source) === 'authenticateApi' &&
			n.arguments[1] &&
			ts.isStringLiteral(n.arguments[1])
		) {
			scope = n.arguments[1].text;
		}
		ts.forEachChild(n, visit);
	};
	visit(node);
	return scope;
}

function scopeTable() {
	const source = parse(join(ROOT, 'src/lib/server/services/tokens.ts'));
	const rows = [];

	const visit = (n) => {
		if (ts.isVariableDeclaration(n) && n.name.getText(source) === 'SCOPES' && n.initializer) {
			const obj = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;
			if (ts.isObjectLiteralExpression(obj)) {
				for (const prop of obj.properties) {
					if (!ts.isPropertyAssignment(prop)) continue;
					const key = prop.name.getText(source).replace(/['"]/g, '');
					const value = ts.isStringLiteral(prop.initializer) ? prop.initializer.text : '';
					rows.push({ key, value });
				}
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);
	return rows;
}

function apiPage() {
	const files = walk(join(ROOT, 'src/routes/api'), (f) => f === '+server.ts');
	const endpoints = [];

	for (const file of files) {
		const source = parse(file);
		const urlPath =
			'/' + relative(join(ROOT, 'src/routes'), dirname(file)).split(/[\\/]/).join('/');

		const moduleDoc = moduleDocOf(source);

		const methods = [];
		for (const st of source.statements) {
			if (!ts.isVariableStatement(st)) continue;
			const isExported = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
			if (!isExported) continue;

			for (const decl of st.declarationList.declarations) {
				const name = decl.name.getText(source);
				if (!/^(GET|POST|PUT|PATCH|DELETE)$/.test(name)) continue;
				methods.push({
					method: name,
					scope: decl.initializer ? scopeIn(decl.initializer, source) : null,
					doc: docOf(st, source, moduleDoc)
				});
			}
		}

		if (methods.length) endpoints.push({ path: urlPath, moduleDoc, methods });
	}

	endpoints.sort((a, b) => a.path.localeCompare(b.path));

	const out = [
		STAMP,
		'# HTTP API\n',
		'Every endpoint under `/api`, read out of the route files themselves — the',
		'methods they export, and the scope each one demands taken from its own',
		'`authenticateApi` call. A handler that changes the scope it requires',
		'changes this page on the next build.\n',
		'## Scopes\n',
		'A token holds some of these and nothing else. Each description is the',
		'sentence somebody agrees to when they grant it.\n',
		'| Scope | What it permits |',
		'| --- | --- |'
	];
	for (const { key, value } of scopeTable()) out.push(`| \`${key}\` | ${value} |`);

	out.push('', '## Endpoints\n');
	out.push('| Endpoint | Method | Scope |');
	out.push('| --- | --- | --- |');
	for (const e of endpoints) {
		for (const m of e.methods) {
			out.push(`| \`${e.path}\` | ${m.method} | ${m.scope ? `\`${m.scope}\`` : '—'} |`);
		}
	}
	out.push('');

	for (const e of endpoints) {
		out.push(`### \`${e.path}\`\n`);
		if (e.moduleDoc) out.push(e.moduleDoc + '\n');
		for (const m of e.methods) {
			out.push(`**${m.method}**${m.scope ? ` — requires \`${m.scope}\`` : ''}\n`);
			if (m.doc) out.push(m.doc + '\n');
		}
	}

	return out.join('\n');
}

/* --------------------------------------------------------------- services */

function servicesPage() {
	const dir = join(ROOT, 'src/lib/server/services');
	const files = readdirSync(dir)
		.filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
		.sort();

	const out = [
		STAMP,
		'# Services\n',
		'Every module in `src/lib/server/services`, with the comment it carries at',
		'the top and the functions it exports. All database access lives here:',
		'routes are adapters that read a form and call one of these, which is why',
		'this list is the closest thing the app has to a table of contents.\n',
		'Collected from the source, so a function renamed or a header rewritten',
		'shows up here on the next build.\n'
	];

	const modules = [];
	for (const file of files) {
		const source = parse(join(dir, file));
		const name = file.replace(/\.ts$/, '');

		const moduleDoc = moduleDocOf(source);

		const exports = [];
		for (const st of source.statements) {
			const isExported = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
			if (!isExported) continue;

			if (ts.isFunctionDeclaration(st) && st.name) {
				const params = st.parameters.map((p) => p.name.getText(source)).join(', ');
				exports.push({
					kind: 'function',
					signature: `${st.name.getText(source)}(${params})`,
					doc: docOf(st, source, moduleDoc)
				});
			} else if (ts.isVariableStatement(st)) {
				for (const decl of st.declarationList.declarations) {
					exports.push({
						kind: 'const',
						signature: decl.name.getText(source),
						doc: docOf(st, source, moduleDoc)
					});
				}
			} else if (ts.isTypeAliasDeclaration(st) || ts.isInterfaceDeclaration(st)) {
				exports.push({
					kind: 'type',
					signature: st.name.getText(source),
					doc: docOf(st, source, moduleDoc)
				});
			}
		}

		modules.push({ name, moduleDoc, exports });
	}

	out.push('| Module | What it is for |', '| --- | --- |');
	for (const m of modules) {
		out.push(
			`| [\`${m.name}\`](#${m.name.replace(/[^a-z0-9]/g, '')}) | ${summary(m.moduleDoc) || '—'} |`
		);
	}
	out.push('');

	for (const m of modules) {
		out.push(`## ${m.name}\n`);
		if (m.moduleDoc) out.push(m.moduleDoc + '\n');

		const fns = m.exports.filter((e) => e.kind === 'function');
		if (fns.length) {
			out.push('### Functions\n');
			for (const f of fns) {
				out.push(`#### \`${f.signature}\`\n`);
				if (f.doc) out.push(f.doc + '\n');
			}
		}

		const types = m.exports.filter((e) => e.kind === 'type');
		if (types.length) {
			out.push('### Types\n');
			for (const t of types) out.push(`- \`${t.signature}\`${t.doc ? ` — ${summary(t.doc)}` : ''}`);
			out.push('');
		}
	}

	return out.join('\n');
}

/* -------------------------------------------------------------- shortcuts */

function shortcutsPage() {
	const source = parse(join(ROOT, 'src/lib/shortcuts.ts'));
	const global = [];
	const pages = [];

	const readBindings = (arr) =>
		arr.elements.filter(ts.isObjectLiteralExpression).map((el) => {
			const get = (key) => {
				const p = el.properties.find(
					(pr) => ts.isPropertyAssignment(pr) && pr.name.getText(source) === key
				);
				return p && ts.isStringLiteral(p.initializer) ? p.initializer.text : '';
			};
			return { key: get('key'), action: get('action'), description: get('description') };
		});

	const visit = (n) => {
		if (ts.isVariableDeclaration(n) && n.initializer) {
			const name = n.name.getText(source);
			if (name === 'GLOBAL_SHORTCUTS' && ts.isArrayLiteralExpression(n.initializer)) {
				global.push(...readBindings(n.initializer));
			}
			if (name === 'PAGE_SHORTCUTS') {
				const obj = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;
				if (ts.isObjectLiteralExpression(obj)) {
					for (const prop of obj.properties) {
						if (!ts.isPropertyAssignment(prop)) continue;
						const path = prop.name.getText(source).replace(/['"]/g, '');
						const value = prop.initializer;
						if (!ts.isObjectLiteralExpression(value)) continue;

						const labelProp = value.properties.find(
							(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === 'label'
						);
						const listProp = value.properties.find(
							(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === 'shortcuts'
						);

						pages.push({
							path,
							label:
								labelProp && ts.isStringLiteral(labelProp.initializer)
									? labelProp.initializer.text
									: path,
							shortcuts:
								listProp && ts.isArrayLiteralExpression(listProp.initializer)
									? readBindings(listProp.initializer)
									: []
						});
					}
				}
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);

	const out = [
		STAMP,
		'# Keyboard\n',
		'The same table the app binds and the `?` sheet renders, so a key that',
		'works is a key listed here and the reverse.\n',
		'## Everywhere\n',
		'| Key | Does |',
		'| --- | --- |'
	];
	for (const s of global) out.push(`| <kbd>${s.key}</kbd> | ${s.description} |`);
	out.push('');

	for (const p of pages.sort((a, b) => a.path.localeCompare(b.path))) {
		out.push(`## ${p.label} — \`${p.path}\`\n`);
		out.push('| Key | Does |', '| --- | --- |');
		for (const s of p.shortcuts) out.push(`| <kbd>${s.key}</kbd> | ${s.description} |`);
		out.push('');
	}

	return out.join('\n');
}

/* ------------------------------------------------------------------ index */

function indexPage(pages) {
	return [
		STAMP,
		'# How ontoplano works\n',
		'A wiki that is built rather than written. Every page here is generated by',
		'`scripts/build-docs.mjs` from something the running app enforces — the',
		'migration snapshot, the route files, the scope table, the shortcut map —',
		'so a change to the logic changes the page on the next build, and a page',
		'cannot quietly stop being true.\n',
		'Run `yarn docs` to rebuild. `yarn docs:check` fails if what is committed',
		'is out of date, which is what keeps the two honest.\n',
		'## Pages\n',
		...pages.map((p) => `- [${p.title}](${p.file}) — ${p.blurb}`),
		'',
		'## What is not here\n',
		'Anything that cannot be derived. The prose explaining *why* a decision was',
		'taken lives in the comment above the code it explains, where it moves with',
		'that code; the hand-written guides for operators — deployment, backups,',
		'billing, the Android build — are in `docs/` beside this directory, because',
		'they describe things outside this repository that no generator can read.'
	].join('\n');
}

/* ------------------------------------------------------------------- main */

const PAGES = [
	{
		file: 'data-model.md',
		title: 'Data model',
		blurb: 'every table and column, from the migration snapshot',
		build: dataModelPage
	},
	{
		file: 'api.md',
		title: 'HTTP API',
		blurb: 'endpoints and the scope each one demands',
		build: apiPage
	},
	{
		file: 'services.md',
		title: 'Services',
		blurb: 'the service layer, module by module',
		build: servicesPage
	},
	{
		file: 'keyboard.md',
		title: 'Keyboard',
		blurb: 'every shortcut, per page',
		build: shortcutsPage
	}
];

/*
 * Formatted by prettier on the way out.
 *
 * The repo checks every file with prettier, so a generator that emits markdown
 * prettier would rewrite gives you two commands that disagree about the same
 * file forever — `yarn docs` writes it, `yarn lint` rejects it. Running its
 * output through the same formatter the repo uses settles that at the source.
 */
const config = (await prettier.resolveConfig(join(ROOT, 'docs/wiki/README.md'))) ?? {};
const format = (text) => prettier.format(text, { ...config, parser: 'markdown' });

const built = new Map();
for (const page of PAGES) built.set(page.file, await format(page.build()));
built.set('README.md', await format(indexPage(PAGES)));

if (CHECK) {
	const stale = [];
	for (const [file, content] of built) {
		const path = join(OUT, file);
		if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(file);
	}
	// Something committed that the generator no longer produces is drift too.
	const extra = existsSync(OUT)
		? readdirSync(OUT).filter((f) => f.endsWith('.md') && !built.has(f))
		: [];

	if (stale.length || extra.length) {
		console.error('The wiki is out of date. Run `yarn docs` and commit the result.\n');
		for (const f of stale) console.error(`  stale:   docs/wiki/${f}`);
		for (const f of extra) console.error(`  orphan:  docs/wiki/${f}`);
		process.exit(1);
	}
	console.log(`docs: ${built.size} pages up to date`);
} else {
	rmSync(OUT, { recursive: true, force: true });
	mkdirSync(OUT, { recursive: true });
	for (const [file, content] of built) writeFileSync(join(OUT, file), content);
	console.log(`docs: wrote ${built.size} pages to docs/wiki/`);
}
