#!/usr/bin/env node
/**
 * Redraw every icon the app ships from the one logo file.
 *
 *   yarn icons            # rewrite static/favicon.svg and static/icons/*
 *   yarn icons --check    # fail if they are out of date, for CI
 *
 * The source is `src/lib/logo/mark.png`, which the app itself draws through
 * `Logo.svelte`. Before this existed the mark was hand-copied into three SVG
 * files and baked into five PNGs, so changing the logo meant finding all of
 * them — which is the same thing as never changing the logo.
 *
 * The mark is a raster now (it was a flat SVG shape, and the artwork that
 * replaced it is not one). Everything is still assembled as SVG and rasterised
 * from there, because the compositing — a ground, a margin, a centred mark — is
 * the same arithmetic either way, and it keeps `favicon.svg` an SVG.
 *
 * PNGs need a rasteriser. `@resvg/resvg-js` is preferred because it comes with
 * the repo; `rsvg-convert` is used if it is on PATH. With neither, the SVGs are
 * still rewritten and the PNGs are reported as stale rather than silently left
 * wrong.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

// Read the two halves of the brand out of the same files the app imports, so
// this script cannot drift from what the running app draws. brand.ts is read
// rather than imported: it is TypeScript, and node does not speak it.
const markFile = join(ROOT, 'src/lib/logo/mark.png');
const brandFile = join(ROOT, 'src/lib/logo/brand.ts');
const mark = readFileSync(markFile);
const brand = readFileSync(brandFile, 'utf8');

const constant = (name) => {
	const m = brand.match(new RegExp(`export const ${name} = ([^;]+);`));
	if (!m) throw new Error(`${relative(ROOT, brandFile)} no longer exports ${name}`);
	return JSON.parse(m[1].trim().replace(/'/g, '"'));
};
const GROUND = constant('BRAND_GROUND');
const ICON_SCALE = constant('ICON_SCALE');
const MASKABLE = constant('MASKABLE_SCALE');
const APPLE = constant('APPLE_SCALE');

/** Every icon is 512 square whatever size the source happens to be. */
const SIZE = 512;

const dataUri = `data:image/png;base64,${mark.toString('base64')}`;
const header = `<!-- Generated by scripts/build-icons.mjs from src/lib/logo/mark.png. Do not edit. -->`;

/**
 * The mark at `scale` of the icon's width, optionally on the brand ground.
 *
 * Only the shapes that get cropped or tiled take a ground: a launcher masks a
 * maskable icon to its own outline and iOS puts the apple-touch icon on an
 * opaque square. A plain icon and the favicon stay transparent, so they sit on
 * a light page and on a dark tab strip equally well.
 */
function icon(scale, ground) {
	const side = SIZE * scale;
	const at = (SIZE - side) / 2;
	return `${header}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  ${ground ? `<rect width="${SIZE}" height="${SIZE}" fill="${ground}"/>` : ''}
  <image x="${at}" y="${at}" width="${side}" height="${side}" preserveAspectRatio="xMidYMid meet" xlink:href="${dataUri}"/>
</svg>
`;
}

/**
 * The same icon, marked as not the real one.
 *
 * Two installed copies of this app on one phone — staging and the instance
 * somebody actually uses — must not be the same picture, or the wrong week
 * goes into the wrong one. The mark is drained of its colour and a band is laid
 * across the foot of it: recognisable as this app at a glance, unmistakably not
 * production at the same glance.
 *
 * A band rather than the word "staging": at the 48 pixels a launcher actually
 * draws, a word is a smudge, and a shape is still a shape. Amber rather than
 * red or green — red means broken and green means fine, and this is neither.
 */
const STAGING_BAND = '#b45309';
// Dev wears blue where staging wears amber — same band, different answer.
const DEV_BAND = '#1d4ed8';

/**
 * `top` is where the band sits, as a fraction of the height.
 *
 * A launcher crops a maskable icon to its own outline — often a circle — so a
 * band at the very foot of one is a band nobody ever sees. The plain icon is
 * never cropped and wears it at the bottom; the maskable one wears it inside
 * the safe area, where a circle, a squircle and a rounded square all keep it.
 */
function bandedIcon(colour, scale, ground, top = 0.82) {
	const side = SIZE * scale;
	const at = (SIZE - side) / 2;
	const band = SIZE * 0.15;
	return `${header}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  <defs>
    <filter id="drained"><feColorMatrix type="saturate" values="0.15"/></filter>
  </defs>
  ${ground ? `<rect width="${SIZE}" height="${SIZE}" fill="${ground}"/>` : ''}
  <image x="${at}" y="${at}" width="${side}" height="${side}" preserveAspectRatio="xMidYMid meet"
    filter="url(#drained)" xlink:href="${dataUri}"/>
  <rect x="0" y="${SIZE * top}" width="${SIZE}" height="${band}" fill="${colour}"/>
</svg>
`;
}

const plain = icon(ICON_SCALE, null);
const maskable = icon(MASKABLE, GROUND);
const apple = icon(APPLE, GROUND);

const stagingIcon = (scale, ground, top) => bandedIcon(STAGING_BAND, scale, ground, top);
const devIcon = (scale, ground, top) => bandedIcon(DEV_BAND, scale, ground, top);

const plainStaging = stagingIcon(ICON_SCALE, null);
const maskableStaging = stagingIcon(MASKABLE, GROUND, 0.62);
const appleStaging = stagingIcon(APPLE, GROUND, 0.78);
const plainDev = devIcon(ICON_SCALE, null);
const maskableDev = devIcon(MASKABLE, GROUND, 0.62);
const appleDev = devIcon(APPLE, GROUND, 0.78);

const svgs = [
	['static/favicon.svg', plain],
	['static/icons/icon.svg', plain],
	['static/icons/icon-maskable.svg', maskable],
	['static/favicon-staging.svg', plainStaging],
	['static/icons/icon-staging.svg', plainStaging],
	['static/icons/icon-maskable-staging.svg', maskableStaging],
	['static/favicon-dev.svg', plainDev],
	['static/icons/icon-dev.svg', plainDev],
	['static/icons/icon-maskable-dev.svg', maskableDev]
];

const pngs = [
	['static/icons/icon-192.png', plain, 192],
	['static/icons/icon-512.png', plain, 512],
	['static/icons/icon-maskable-192.png', maskable, 192],
	['static/icons/icon-maskable-512.png', maskable, 512],
	// iOS ignores the manifest and reads this one; it is never masked, so it
	// is the mark at almost full size on the ground, at the size Apple asks for.
	['static/icons/apple-touch-icon.png', apple, 180],
	// …and the staging set, which the manifest route and app.html reach for
	// when ONTOPLANO_STAGING is on. Built here rather than by hand, so the day
	// the logo changes both sets change with it.
	['static/icons/icon-192-staging.png', plainStaging, 192],
	['static/icons/icon-512-staging.png', plainStaging, 512],
	['static/icons/icon-maskable-192-staging.png', maskableStaging, 192],
	['static/icons/icon-maskable-512-staging.png', maskableStaging, 512],
	['static/icons/apple-touch-icon-staging.png', appleStaging, 180],
	// …and the dev set, worn by `make dev` so the phone-installed dev PWA and
	// the real app are never the same tile.
	['static/icons/icon-192-dev.png', plainDev, 192],
	['static/icons/icon-512-dev.png', plainDev, 512],
	['static/icons/icon-maskable-192-dev.png', maskableDev, 192],
	['static/icons/icon-maskable-512-dev.png', maskableDev, 512],
	['static/icons/apple-touch-icon-dev.png', appleDev, 180]
];

// ── Rasterising ──────────────────────────────────────────────────────────────

const rasteriser = await (async () => {
	try {
		const { Resvg } = await import('@resvg/resvg-js');
		return {
			name: '@resvg/resvg-js',
			run: (svg, size) =>
				new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng(),
			/** Raw RGBA, for measuring the artwork rather than drawing it. */
			raw: (svg, size) => {
				const out = new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render();
				return { pixels: out.pixels, width: out.width, height: out.height };
			}
		};
	} catch {
		/* not installed — try the system one */
	}
	try {
		execFileSync('rsvg-convert', ['--version'], { stdio: 'ignore' });
		return {
			name: 'rsvg-convert',
			run: (svg, size) =>
				execFileSync('rsvg-convert', ['-w', String(size), '-h', String(size)], { input: svg })
		};
	} catch {
		return null;
	}
})();

// ── The mark's own outline ───────────────────────────────────────────────────

/**
 * The shape of the mark, as a CSS polygon.
 *
 * The phone bar's raised button used to be a circle with the mark inside it,
 * which reads as two shapes where there is one. Clipping the button to the
 * mark's own outline makes the button *be* the mark — but the outline is a
 * property of the artwork, so it is measured from the artwork rather than typed
 * out and left to rot the first time the logo changes.
 *
 * Measured by casting rays from the centre and finding where the alpha stops,
 * then keeping the local maxima — which for a convex polygon are its corners.
 * Written into `src/lib/logo/mark-shape.ts`, which the stylesheet reads.
 */
function outlinePolygon() {
	if (!rasteriser || rasteriser.name !== '@resvg/resvg-js') return null;

	const SAMPLE = 256;
	const svg = `${header}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${SAMPLE}" height="${SAMPLE}"><image width="${SAMPLE}" height="${SAMPLE}" preserveAspectRatio="xMidYMid meet" xlink:href="${dataUri}"/></svg>`;

	const rendered = rasteriser.raw(svg, SAMPLE);
	if (!rendered) return null;
	const { pixels, width, height } = rendered;

	const opaque = (x, y) => {
		if (x < 0 || y < 0 || x >= width || y >= height) return false;
		return pixels[(y * width + x) * 4 + 3] > 24;
	};

	const cx = width / 2;
	const cy = height / 2;
	const STEPS = 720;
	const radii = [];

	for (let i = 0; i < STEPS; i++) {
		const angle = (i / STEPS) * Math.PI * 2;
		const dx = Math.cos(angle);
		const dy = Math.sin(angle);
		let hit = 0;
		// Outwards in, so a hole in the middle of the artwork cannot be mistaken
		// for its edge.
		for (let r = Math.min(cx, cy); r > 0; r -= 0.5) {
			if (opaque(Math.round(cx + dx * r), Math.round(cy + dy * r))) {
				hit = r;
				break;
			}
		}
		radii.push(hit);
	}

	// A corner is where the radius is a local maximum. Smoothed first, or the
	// anti-aliased edge produces a maximum every few degrees.
	const smooth = radii.map((_, i) => {
		let sum = 0;
		for (let k = -4; k <= 4; k++) sum += radii[(i + k + STEPS) % STEPS];
		return sum / 9;
	});

	const corners = [];
	const WINDOW = 20;
	for (let i = 0; i < STEPS; i++) {
		let isMax = true;
		for (let k = -WINDOW; k <= WINDOW; k++) {
			if (smooth[(i + k + STEPS) % STEPS] > smooth[i] + 1e-9) {
				isMax = false;
				break;
			}
		}
		if (!isMax) continue;
		// One corner per plateau: an exactly flat run would otherwise give one
		// point per sample.
		const angle = (i / STEPS) * Math.PI * 2;
		const last = corners[corners.length - 1];
		if (last && Math.abs(angle - last.angle) < 0.25) continue;
		corners.push({ angle, r: radii[i] });
	}

	// The wrap-around: the last corner and the first are the same corner when
	// the ray sweep comes back round to where it started.
	if (
		corners.length > 3 &&
		Math.abs(corners[0].angle + Math.PI * 2 - corners[corners.length - 1].angle) < 0.25
	) {
		corners.pop();
	}

	if (corners.length < 3) return null;

	return corners
		.map(({ angle, r }) => {
			const x = ((cx + Math.cos(angle) * r) / width) * 100;
			const y = ((cy + Math.sin(angle) * r) / height) * 100;
			return `${x.toFixed(2)}% ${y.toFixed(2)}%`;
		})
		.join(', ');
}

// ── Writing ──────────────────────────────────────────────────────────────────

let stale = 0;
const write = (path, bytes) => {
	const full = join(ROOT, path);
	const before = existsSync(full) ? readFileSync(full) : null;
	const same = before && Buffer.compare(before, Buffer.from(bytes)) === 0;
	if (same) return;
	stale++;
	if (CHECK) {
		console.log(`  stale  ${path}`);
		return;
	}
	writeFileSync(full, bytes);
	console.log(`  wrote  ${path}`);
};

console.log(
	`ontoplano icons, from ${relative(ROOT, markFile)} (${createHash('sha256').update(mark).digest('hex').slice(0, 8)})`
);
for (const [path, svg] of svgs) write(path, svg);

if (rasteriser) {
	console.log(`  PNGs drawn by ${rasteriser.name}`);
	for (const [path, svg, size] of pngs) write(path, rasteriser.run(svg, size));
} else {
	console.log('  no rasteriser (@resvg/resvg-js or rsvg-convert) — the PNGs were left alone');
	console.log('  install one and run this again, or the app icon stays on the old mark');
	stale += pngs.length;
}

const polygon = outlinePolygon();
if (polygon) {
	write(
		'src/lib/logo/mark-shape.ts',
		`${'/'}**\n * The mark's own outline, measured from \`mark.png\` by \`yarn icons\`.\n *\n * Do not edit: replace the logo and run \`yarn icons\` instead. It is what lets\n * the phone bar's raised button be the shape of the mark rather than a circle\n * with the mark inside it.\n */\nexport const MARK_CLIP_PATH =\n\t'polygon(${polygon})';\n`
	);
} else {
	console.log('  no rasteriser — src/lib/logo/mark-shape.ts left alone');
}

if (CHECK && stale) {
	console.error(`\n${stale} icon(s) out of date. Run: yarn icons`);
	process.exit(1);
}
console.log(stale ? `\n${stale} icon(s) redrawn.` : '\nEverything was already up to date.');
