#!/usr/bin/env node
/**
 * Redraw every icon the app ships from the one logo file.
 *
 *   yarn icons            # rewrite static/favicon.svg and static/icons/*
 *   yarn icons --check    # fail if they are out of date, for CI
 *
 * The source is `src/lib/logo/mark.png`, which the app itself draws through
 * `Logo.svelte`. Before this existed the mark was hand-copied into three SVG
 * files and baked into five PNGs, so changing the logo meant finding all of
 * them — which is the same thing as never changing the logo.
 *
 * The mark is a raster now (it was a flat SVG shape, and the artwork that
 * replaced it is not one). Everything is still assembled as SVG and rasterised
 * from there, because the compositing — a ground, a margin, a centred mark — is
 * the same arithmetic either way, and it keeps `favicon.svg` an SVG.
 *
 * PNGs need a rasteriser. `@resvg/resvg-js` is preferred because it comes with
 * the repo; `rsvg-convert` is used if it is on PATH. With neither, the SVGs are
 * still rewritten and the PNGs are reported as stale rather than silently left
 * wrong.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

// Read the two halves of the brand out of the same files the app imports, so
// this script cannot drift from what the running app draws. brand.ts is read
// rather than imported: it is TypeScript, and node does not speak it.
const markFile = join(ROOT, 'src/lib/logo/mark.png');
const brandFile = join(ROOT, 'src/lib/logo/brand.ts');
const mark = readFileSync(markFile);
const brand = readFileSync(brandFile, 'utf8');

const constant = (name) => {
	const m = brand.match(new RegExp(`export const ${name} = ([^;]+);`));
	if (!m) throw new Error(`${relative(ROOT, brandFile)} no longer exports ${name}`);
	return JSON.parse(m[1].trim().replace(/'/g, '"'));
};
const GROUND = constant('BRAND_GROUND');
const ICON_SCALE = constant('ICON_SCALE');
const MASKABLE = constant('MASKABLE_SCALE');
const APPLE = constant('APPLE_SCALE');

/** Every icon is 512 square whatever size the source happens to be. */
const SIZE = 512;

const dataUri = `data:image/png;base64,${mark.toString('base64')}`;
const header = `<!-- Generated by scripts/build-icons.mjs from src/lib/logo/mark.png. Do not edit. -->`;

/**
 * The mark at `scale` of the icon's width, optionally on the brand ground.
 *
 * Only the shapes that get cropped or tiled take a ground: a launcher masks a
 * maskable icon to its own outline and iOS puts the apple-touch icon on an
 * opaque square. A plain icon and the favicon stay transparent, so they sit on
 * a light page and on a dark tab strip equally well.
 */
function icon(scale, ground) {
	const side = SIZE * scale;
	const at = (SIZE - side) / 2;
	return `${header}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  ${ground ? `<rect width="${SIZE}" height="${SIZE}" fill="${ground}"/>` : ''}
  <image x="${at}" y="${at}" width="${side}" height="${side}" preserveAspectRatio="xMidYMid meet" xlink:href="${dataUri}"/>
</svg>
`;
}

const plain = icon(ICON_SCALE, null);
const maskable = icon(MASKABLE, GROUND);
const apple = icon(APPLE, GROUND);

const svgs = [
	['static/favicon.svg', plain],
	['static/icons/icon.svg', plain],
	['static/icons/icon-maskable.svg', maskable]
];

const pngs = [
	['static/icons/icon-192.png', plain, 192],
	['static/icons/icon-512.png', plain, 512],
	['static/icons/icon-maskable-192.png', maskable, 192],
	['static/icons/icon-maskable-512.png', maskable, 512],
	// iOS ignores the manifest and reads this one; it is never masked, so it
	// is the mark at almost full size on the ground, at the size Apple asks for.
	['static/icons/apple-touch-icon.png', apple, 180]
];

// ── Rasterising ──────────────────────────────────────────────────────────────

const rasteriser = await (async () => {
	try {
		const { Resvg } = await import('@resvg/resvg-js');
		return {
			name: '@resvg/resvg-js',
			run: (svg, size) => new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng()
		};
	} catch {
		/* not installed — try the system one */
	}
	try {
		execFileSync('rsvg-convert', ['--version'], { stdio: 'ignore' });
		return {
			name: 'rsvg-convert',
			run: (svg, size) =>
				execFileSync('rsvg-convert', ['-w', String(size), '-h', String(size)], { input: svg })
		};
	} catch {
		return null;
	}
})();

// ── Writing ──────────────────────────────────────────────────────────────────

let stale = 0;
const write = (path, bytes) => {
	const full = join(ROOT, path);
	const before = existsSync(full) ? readFileSync(full) : null;
	const same = before && Buffer.compare(before, Buffer.from(bytes)) === 0;
	if (same) return;
	stale++;
	if (CHECK) {
		console.log(`  stale  ${path}`);
		return;
	}
	writeFileSync(full, bytes);
	console.log(`  wrote  ${path}`);
};

console.log(
	`ontoplano icons, from ${relative(ROOT, markFile)} (${createHash('sha256').update(mark).digest('hex').slice(0, 8)})`
);
for (const [path, svg] of svgs) write(path, svg);

if (rasteriser) {
	console.log(`  PNGs drawn by ${rasteriser.name}`);
	for (const [path, svg, size] of pngs) write(path, rasteriser.run(svg, size));
} else {
	console.log('  no rasteriser (@resvg/resvg-js or rsvg-convert) — the PNGs were left alone');
	console.log('  install one and run this again, or the app icon stays on the old mark');
	stale += pngs.length;
}

if (CHECK && stale) {
	console.error(`\n${stale} icon(s) out of date. Run: yarn icons`);
	process.exit(1);
}
console.log(stale ? `\n${stale} icon(s) redrawn.` : '\nEverything was already up to date.');
