#!/usr/bin/env node
/**
 * Redraw every icon the app ships from the one logo file.
 *
 *   yarn icons            # rewrite static/favicon.svg and static/icons/*
 *   yarn icons --check    # fail if they are out of date, for CI
 *
 * The source is `src/lib/logo/mark.png`, which the app itself draws through
 * `Logo.svelte`. Before this existed the mark was hand-copied into three SVG
 * files and baked into five PNGs, so changing the logo meant finding all of
 * them — which is the same thing as never changing the logo.
 *
 * The mark is a raster now (it was a flat SVG shape, and the artwork that
 * replaced it is not one). Everything is still assembled as SVG and rasterised
 * from there, because the compositing — a ground, a margin, a centred mark — is
 * the same arithmetic either way, and it keeps `favicon.svg` an SVG.
 *
 * PNGs need a rasteriser. `@resvg/resvg-js` is preferred because it comes with
 * the repo; `rsvg-convert` is used if it is on PATH. With neither, the SVGs are
 * still rewritten and the PNGs are reported as stale rather than silently left
 * wrong.
 */
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

// Read the two halves of the brand out of the same files the app imports, so
// this script cannot drift from what the running app draws. brand.ts is read
// rather than imported: it is TypeScript, and node does not speak it.
const markFile = join(ROOT, 'src/lib/logo/mark.png');
const brandFile = join(ROOT, 'src/lib/logo/brand.ts');
const mark = readFileSync(markFile);
const brand = readFileSync(brandFile, 'utf8');

const constant = (name) => {
	const m = brand.match(new RegExp(`export const ${name} = ([^;]+);`));
	if (!m) throw new Error(`${relative(ROOT, brandFile)} no longer exports ${name}`);
	return JSON.parse(m[1].trim().replace(/'/g, '"'));
};
const GROUND = constant('BRAND_GROUND');
/** How much colour a marked-as-not-real icon keeps. The app uses the same. */
const DRAINED = constant('MARK_DRAINED');

/**
 * The mark's own dark, read from where the app reads it.
 *
 * `mark-shape.ts` holds it because the wheel and the phone bar are painted in
 * it too — it is the colour inside the drawing, sampled off the artwork, not a
 * background somebody chose. An icon that has to be opaque wants exactly that
 * one: the outermost ring of the mark then continues into the corners instead
 * of ending at a square edge somebody picked a colour for.
 */
const shapeFile = join(ROOT, 'src/lib/logo/mark-shape.ts');
const shape = readFileSync(shapeFile, 'utf8');
/** What the last run measured, for the case where this one cannot measure. */
const previous = (name, fallback) => {
	const m = shape.match(new RegExp(`export const ${name} = '?([^';]+)'?;`));
	return m ? m[1].trim() : fallback;
};
const ICON_SCALE = constant('ICON_SCALE');
const MASKABLE = constant('MASKABLE_SCALE');
const APPLE = constant('APPLE_SCALE');
const SOLID = constant('SOLID_SCALE');
/** How much colour a marked-as-not-real icon keeps, and how far its field is
 *  lifted. Both live in brand.ts; the app applies the same two numbers. */
const LIFT = constant('MARK_FIELD_LIFT');

/** Every icon is 512 square whatever size the source happens to be. */
const SIZE = 512;
/** The square the artwork is sampled at to be measured rather than drawn. */
const SAMPLE = 256;

/**
 * How far a pixel may be from the field's colour and still count as the field.
 * Wide enough for the drawing's own anti-aliasing, narrow enough to leave the
 * ring's darkest colours alone.
 */
const FIELD_TOLERANCE = 45;

/*
 * The drawing is measured before anything is drawn from it.
 *
 * It used to be measured at the end, after the icons had already been
 * assembled — which meant everything derived from the artwork on the run that
 * replaced it was derived from the *previous* artwork's numbers, and only came
 * right the second time `yarn icons` was run. Nothing said so. Measuring first
 * and drawing from the answer is one pass and no stale middle state.
 */
const polygon = outlinePolygon();
const parts = polygon ? markParts(polygon) : null;

const FIELD = parts?.field ?? previous('MARK_FIELD', '#202830');
const MIDDLE = parts ? parts.middle : Number(previous('MARK_MIDDLE', '0.48'));
const LIFTED_FIELD = lifted(FIELD, LIFT);

const dataUri = `data:image/png;base64,${mark.toString('base64')}`;
/** The same drawing with its field lifted, for every icon that is drained. */
const liftedPng = liftedMark();
const liftedUri = liftedPng
	? `data:image/png;base64,${Buffer.from(liftedPng).toString('base64')}`
	: dataUri;
const header = `<!-- Generated by scripts/build-icons.mjs from src/lib/logo/mark.png. Do not edit. -->`;

/** A colour moved `amount` of the way to white — how the field is lifted. */
function lifted(hex, amount) {
	const channel = (at) => parseInt(hex.slice(at, at + 2), 16);
	const mix = (c) => Math.round(c + (255 - c) * amount);
	return `#${[channel(1), channel(3), channel(5)]
		.map((c) => mix(c).toString(16).padStart(2, '0'))
		.join('')}`;
}

/**
 * The mark at `scale` of the icon's width, optionally on the brand ground.
 *
 * Only the shapes that get cropped or tiled take a ground: a launcher masks a
 * maskable icon to its own outline and iOS puts the apple-touch icon on an
 * opaque square. A plain icon and the favicon stay transparent, so they sit on
 * a light page and on a dark tab strip equally well.
 */
function icon(scale, ground) {
	const side = SIZE * scale;
	const at = (SIZE - side) / 2;
	return `${header}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  ${ground ? `<rect width="${SIZE}" height="${SIZE}" fill="${ground}"/>` : ''}
  <image x="${at}" y="${at}" width="${side}" height="${side}" preserveAspectRatio="xMidYMid meet" xlink:href="${dataUri}"/>
</svg>
`;
}

/**
 * The same icon, marked as not the real one.
 *
 * Two installed copies of this app on one phone — staging and the instance
 * somebody actually uses — must not be the same picture, or the wrong week
 * goes into the wrong one. The mark is drained of its colour, its own dark is
 * lifted so the middle does not close up into a disc, and a band is laid across
 * the foot of it: recognisable as this app at a glance, unmistakably not
 * production at the same glance.
 *
 * A band rather than the word "staging": at the 48 pixels a launcher actually
 * draws, a word is a smudge, and a shape is still a shape. Amber rather than
 * red or green — red means broken and green means fine, and this is neither.
 */
const STAGING_BAND = '#b45309';
// Dev wears blue where staging wears amber — same band, different answer.
const DEV_BAND = '#1d4ed8';

/**
 * `top` is where the band sits, as a fraction of the height.
 *
 * A launcher crops a maskable icon to its own outline — often a circle — so a
 * band at the very foot of one is a band nobody ever sees. The plain icon is
 * never cropped and wears it at the bottom; the maskable one wears it inside
 * the safe area, where a circle, a squircle and a rounded square all keep it.
 */
function bandedIcon(colour, scale, ground, top = 0.82) {
	const side = SIZE * scale;
	const at = (SIZE - side) / 2;
	const band = SIZE * 0.15;
	return `${header}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  <defs>
    <filter id="drained"><feColorMatrix type="saturate" values="${DRAINED}"/></filter>
  </defs>
  ${ground ? `<rect width="${SIZE}" height="${SIZE}" fill="${ground}"/>` : ''}
  <image x="${at}" y="${at}" width="${side}" height="${side}" preserveAspectRatio="xMidYMid meet"
    filter="url(#drained)" xlink:href="${liftedUri}"/>
  <rect x="0" y="${SIZE * top}" width="${SIZE}" height="${band}" fill="${colour}"/>
</svg>
`;
}

const plain = icon(ICON_SCALE, null);
/*
 * The same icon with nothing transparent about it.
 *
 * Every other icon here leaves the corners empty, which is right for a tile a
 * launcher masks and wrong everywhere transparency is refused — a store
 * listing above all, where an icon with an alpha channel is rejected on
 * upload. On the mark's own dark the ring reads as running off the edge rather
 * than as a shape pasted onto a square.
 *
 * It keeps a margin of its own: nothing crops this one, so the room around the
 * mark has to be drawn rather than left to a mask.
 */
const solid = icon(SOLID, FIELD);
const maskable = icon(MASKABLE, GROUND);
const apple = icon(APPLE, GROUND);

const stagingIcon = (scale, ground, top) => bandedIcon(STAGING_BAND, scale, ground, top);
const devIcon = (scale, ground, top) => bandedIcon(DEV_BAND, scale, ground, top);

const plainStaging = stagingIcon(ICON_SCALE, null);
const maskableStaging = stagingIcon(MASKABLE, GROUND, 0.62);
const appleStaging = stagingIcon(APPLE, GROUND, 0.78);
const plainDev = devIcon(ICON_SCALE, null);
const maskableDev = devIcon(MASKABLE, GROUND, 0.62);
const appleDev = devIcon(APPLE, GROUND, 0.78);

const svgs = [
	['static/favicon.svg', plain],
	['static/icons/icon.svg', plain],
	['static/icons/icon-maskable.svg', maskable],
	['static/icons/icon-solid.svg', solid],
	['static/favicon-staging.svg', plainStaging],
	['static/icons/icon-staging.svg', plainStaging],
	['static/icons/icon-maskable-staging.svg', maskableStaging],
	['static/favicon-dev.svg', plainDev],
	['static/icons/icon-dev.svg', plainDev],
	['static/icons/icon-maskable-dev.svg', maskableDev]
];

const pngs = [
	['static/icons/icon-192.png', plain, 192],
	['static/icons/icon-512.png', plain, 512],
	['static/icons/icon-maskable-192.png', maskable, 192],
	['static/icons/icon-maskable-512.png', maskable, 512],
	// The one with no alpha at all, for anywhere that refuses it.
	['static/icons/icon-512-solid.png', solid, 512],
	// iOS ignores the manifest and reads this one; it is never masked, so it
	// is the mark at almost full size on the ground, at the size Apple asks for.
	['static/icons/apple-touch-icon.png', apple, 180],
	// …and the staging set, which the manifest route and app.html reach for
	// when ONTOPLANO_STAGING is on. Built here rather than by hand, so the day
	// the logo changes both sets change with it.
	['static/icons/icon-192-staging.png', plainStaging, 192],
	['static/icons/icon-512-staging.png', plainStaging, 512],
	['static/icons/icon-maskable-192-staging.png', maskableStaging, 192],
	['static/icons/icon-maskable-512-staging.png', maskableStaging, 512],
	['static/icons/apple-touch-icon-staging.png', appleStaging, 180],
	// …and the dev set, worn by `make dev` so the phone-installed dev PWA and
	// the real app are never the same tile.
	['static/icons/icon-192-dev.png', plainDev, 192],
	['static/icons/icon-512-dev.png', plainDev, 512],
	['static/icons/icon-maskable-192-dev.png', maskableDev, 192],
	['static/icons/icon-maskable-512-dev.png', maskableDev, 512],
	['static/icons/apple-touch-icon-dev.png', appleDev, 180]
];

// ── Rasterising ──────────────────────────────────────────────────────────────

const rasteriser = await (async () => {
	try {
		const { Resvg } = await import('@resvg/resvg-js');
		return {
			name: '@resvg/resvg-js',
			run: (svg, size) =>
				new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng(),
			/** Raw RGBA, for measuring the artwork rather than drawing it. */
			raw: (svg, size) => {
				const out = new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render();
				return { pixels: out.pixels, width: out.width, height: out.height };
			}
		};
	} catch {
		/* not installed — try the system one */
	}
	try {
		execFileSync('rsvg-convert', ['--version'], { stdio: 'ignore' });
		return {
			name: 'rsvg-convert',
			run: (svg, size) =>
				execFileSync('rsvg-convert', ['-w', String(size), '-h', String(size)], { input: svg })
		};
	} catch {
		return null;
	}
})();

// ── The mark's own outline ───────────────────────────────────────────────────

/**
 * The shape of the mark, as a CSS polygon.
 *
 * The phone bar's raised button used to be a circle with the mark inside it,
 * which reads as two shapes where there is one. Clipping the button to the
 * mark's own outline makes the button *be* the mark — but the outline is a
 * property of the artwork, so it is measured from the artwork rather than typed
 * out and left to rot the first time the logo changes.
 *
 * Measured by casting rays from the centre and finding where the alpha stops,
 * then keeping the local maxima — which for a convex polygon are its corners.
 * Written into `src/lib/logo/mark-shape.ts`, which the stylesheet reads.
 *
 * The pixels come from decoding the mark itself rather than from re-rendering
 * it inside an SVG: wrapped that way it comes back inset by a few per cent,
 * and an outline measured from the inset copy draws the bar's button a sixth
 * too small with its points cut off — which is exactly what happened the first
 * time the mark was exported edge to edge rather than on a plate.
 */

/** The mark's alpha at `SAMPLE` square, or null if nothing here can decode it. */
function markAlpha() {
	try {
		const raw = execFileSync(
			'magick',
			[markFile, '-resize', `${SAMPLE}x${SAMPLE}!`, '-depth', '8', 'rgba:-'],
			{ maxBuffer: SAMPLE * SAMPLE * 4 * 2 }
		);
		if (raw.length !== SAMPLE * SAMPLE * 4) return null;
		return { pixels: raw, width: SAMPLE, height: SAMPLE };
	} catch {
		return null;
	}
}

function outlinePolygon() {
	const rendered = markAlpha();
	if (!rendered) return null;
	const { pixels, width, height } = rendered;
	const opaque = (x, y) => pixels[(y * width + x) * 4 + 3] > 24;

	/*
	 * The outline is the convex hull of what is painted.
	 *
	 * Rays from the centre were the first attempt and they cannot describe a
	 * mark that reaches the edge of its own canvas: a ray has to stop at the
	 * frame, so the shape it measures is the frame. A hull has no such limit,
	 * it is exact for any convex mark, and for an octagon it comes back as the
	 * octagon — with a few extra points along each side from the anti-aliased
	 * edge, which the collinear pass below drops.
	 */
	const points = [];
	for (let y = 0; y < height; y++) {
		let first = -1;
		let last = -1;
		for (let x = 0; x < width; x++) {
			if (!opaque(x, y)) continue;
			if (first < 0) first = x;
			last = x;
		}
		if (first >= 0) {
			points.push([first, y]);
			points.push([last, y]);
		}
	}
	if (points.length < 6) return null;

	// Andrew's monotone chain.
	points.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
	const cross = (o, a, b) => (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);
	const half = (list) => {
		const out = [];
		for (const p of list) {
			while (out.length > 1 && cross(out[out.length - 2], out[out.length - 1], p) <= 0) out.pop();
			out.push(p);
		}
		out.pop();
		return out;
	};
	const hull = [...half(points), ...half([...points].reverse())];
	if (hull.length < 3) return null;

	/*
	 * A corner is where the outline changes direction.
	 *
	 * The hull has a point for every row the anti-aliased edge touches, so the
	 * sides arrive as long runs of nearly parallel edges. Grouping consecutive
	 * edges that keep within a few degrees of the run they started leaves one
	 * point per real corner — eight for an octagon, and whatever another mark
	 * actually has. Measuring the turn rather than the distance from a chord is
	 * what keeps a long straight side from swallowing the corner at its end.
	 */
	const TURN = (15 * Math.PI) / 180;
	const heading = (a, b) => Math.atan2(b[1] - a[1], b[0] - a[0]);
	const apart = (a, b) => {
		const d = Math.abs(a - b) % (Math.PI * 2);
		return d > Math.PI ? Math.PI * 2 - d : d;
	};

	const simplified = [];
	let runFrom = heading(hull[0], hull[1 % hull.length]);
	for (let i = 0; i < hull.length; i++) {
		const to = heading(hull[i], hull[(i + 1) % hull.length]);
		if (apart(to, runFrom) > TURN) {
			simplified.push(hull[i]);
			runFrom = to;
		}
	}
	if (simplified.length < 3) return null;

	/*
	 * A corner is one point, not two.
	 *
	 * Rasterised at this size a corner is a short flat cap rather than a point,
	 * so both of its ends read as a turn and every vertex comes out doubled.
	 * Anything within a few pixels of the last corner is the same corner, and
	 * the pair averages to where the corner actually is.
	 */
	const TOGETHER = width * 0.03;
	const merged = [];
	for (const point of simplified) {
		const last = merged[merged.length - 1];
		if (last && Math.hypot(point[0] - last.x / last.n, point[1] - last.y / last.n) < TOGETHER) {
			last.x += point[0];
			last.y += point[1];
			last.n++;
			continue;
		}
		merged.push({ x: point[0], y: point[1], n: 1 });
	}
	// The first and the last are the same corner when the walk comes back round.
	if (merged.length > 3) {
		const first = merged[0];
		const last = merged[merged.length - 1];
		if (
			Math.hypot(first.x / first.n - last.x / last.n, first.y / first.n - last.y / last.n) <
			TOGETHER
		) {
			first.x += last.x;
			first.y += last.y;
			first.n += last.n;
			merged.pop();
		}
	}
	const corners = merged.map(({ x, y, n }) => [x / n, y / n]);
	if (corners.length < 3) return null;

	return corners
		.map(
			([x, y]) =>
				`${((x / (width - 1)) * 100).toFixed(2)}% ${((y / (height - 1)) * 100).toFixed(2)}%`
		)
		.join(', ');
}

// ── Writing ──────────────────────────────────────────────────────────────────

let stale = 0;
const write = (path, bytes) => {
	const full = join(ROOT, path);
	const before = existsSync(full) ? readFileSync(full) : null;
	const same = before && Buffer.compare(before, Buffer.from(bytes)) === 0;
	if (same) return;
	stale++;
	if (CHECK) {
		console.log(`  stale  ${path}`);
		return;
	}
	writeFileSync(full, bytes);
	console.log(`  wrote  ${path}`);
};

console.log(
	`ontoplano icons, from ${relative(ROOT, markFile)} (${createHash('sha256').update(mark).digest('hex').slice(0, 8)})`
);
for (const [path, svg] of svgs) write(path, svg);

if (rasteriser) {
	console.log(`  PNGs drawn by ${rasteriser.name}`);
	for (const [path, svg, size] of pngs) write(path, rasteriser.run(svg, size));
} else {
	console.log('  no rasteriser (@resvg/resvg-js or rsvg-convert) — the PNGs were left alone');
	console.log('  install one and run this again, or the app icon stays on the old mark');
	stale += pngs.length;
}

/*
 * The mark with its field knocked out, for a ground of somebody else's choosing.
 *
 * The drawing carries its own dark field between the ring and the medallion.
 * That is right nearly everywhere — it is what lets the mark sit on a white
 * card and on the app's dark bar without a halo — and wrong in the one place
 * the mark is meant to be a window: the instance chooser, where the ring
 * should be a ring of colour with the page showing through it.
 *
 * Derived rather than drawn, so replacing `mark.png` cannot leave a stale
 * second logo behind: every pixel outside the medallion that is within a
 * hair of the field's colour loses its alpha, and nothing else is touched. The
 * medallion is left alone even where it is dark, or the shading inside it
 * would come out full of holes.
 */
function hollowMark() {
	let PNG;
	try {
		({ PNG } = createRequire(import.meta.url)('pngjs'));
	} catch {
		return null;
	}

	const target = [1, 3, 5].map((i) => parseInt(FIELD.slice(i, i + 2), 16));
	const png = PNG.sync.read(mark);
	const { width, height, data } = png;
	const half = width / 2;

	for (let y = 0; y < height; y += 1) {
		for (let x = 0; x < width; x += 1) {
			const i = (y * width + x) << 2;
			if (data[i + 3] === 0) continue;
			if (Math.hypot(x - half, y - height / 2) / half < MIDDLE) continue;
			const off =
				Math.abs(data[i] - target[0]) +
				Math.abs(data[i + 1] - target[1]) +
				Math.abs(data[i + 2] - target[2]);
			if (off <= FIELD_TOLERANCE) data[i + 3] = 0;
		}
	}
	return PNG.sync.write(png);
}

/*
 * The mark with its field lifted, for the copy that is not the ordinary one.
 *
 * The sibling of `hollowMark`, and the same pixels either way: everything
 * outside the middle that is within a hair of the field's colour. One derivation
 * takes the alpha away so the page shows through; this one repaints it a little
 * nearer white, so a drained mark still reads as a drawing at the size a
 * launcher draws it instead of closing up into a dark disc.
 *
 * Only the field moves. The ring keeps its colours — draining is what takes
 * those — and anything inside the middle is left alone, or the shading in it
 * would come out blotched.
 */
function liftedMark() {
	let PNG;
	try {
		({ PNG } = createRequire(import.meta.url)('pngjs'));
	} catch {
		return null;
	}

	const target = [1, 3, 5].map((i) => parseInt(FIELD.slice(i, i + 2), 16));
	const to = [1, 3, 5].map((i) => parseInt(LIFTED_FIELD.slice(i, i + 2), 16));
	const png = PNG.sync.read(mark);
	const { width, height, data } = png;
	const half = width / 2;

	for (let y = 0; y < height; y += 1) {
		for (let x = 0; x < width; x += 1) {
			const i = (y * width + x) << 2;
			if (data[i + 3] === 0) continue;
			if (Math.hypot(x - half, y - height / 2) / half < MIDDLE) continue;
			const off =
				Math.abs(data[i] - target[0]) +
				Math.abs(data[i + 1] - target[1]) +
				Math.abs(data[i + 2] - target[2]);
			if (off > FIELD_TOLERANCE) continue;
			data[i] = to[0];
			data[i + 1] = to[1];
			data[i + 2] = to[2];
		}
	}
	return PNG.sync.write(png);
}

/**
 * Where the mark's ring ends and its middle begins, as a fraction of the half
 * width — and the colour of each of the ring's sides.
 *
 * The wheel the rooms open in is the mark at two hundred and ninety pixels:
 * its ring is the wheel's rim and its middle is the hole you let go in. Both
 * of those are properties of the drawing, so both are measured off it here
 * rather than typed into a component as numbers that were right in September.
 *
 * The ring is read along a ray from the centre: the middle is coloured, the
 * field between the middle and the ring is nearly black, and the ring is
 * coloured again. The first dark pixel going outward is the edge of the
 * middle; the colour at the outermost band, sampled at the midpoint of each
 * side, is what that side is painted.
 */
function markParts(polygon) {
	const rendered = markAlpha();
	if (!rendered || !polygon) return null;
	const { pixels, width, height } = rendered;
	const cx = width / 2;
	const cy = height / 2;

	/** The outline's corners, back in pixels of the sampled raster. */
	const corners = (polygon.match(/[\d.]+%\s+[\d.]+%/g) ?? []).map((pair) => {
		const [x, y] = pair.split(/\s+/).map((n) => (parseFloat(n) / 100) * width);
		return [x, y];
	});
	if (corners.length < 3) return null;

	const at = (x, y) => {
		const i = (Math.round(y) * width + Math.round(x)) * 4;
		return { r: pixels[i], g: pixels[i + 1], b: pixels[i + 2], a: pixels[i + 3] };
	};
	/** Near-black: the field the wedges are laid into. */
	const dark = (p) => p.a > 24 && p.r + p.g + p.b < 150;

	// Outward from the middle, in eight directions, and the smallest answer —
	// so a medallion that is not quite centred is not read as bigger than it is.
	let middle = 1;
	for (let k = 0; k < 8; k++) {
		const angle = (k / 8) * Math.PI * 2;
		for (let r = 4; r < cx; r++) {
			const p = at(cx + Math.cos(angle) * r, cy + Math.sin(angle) * r);
			if (dark(p)) {
				middle = Math.min(middle, r / cx);
				break;
			}
		}
	}

	/*
	 * And each side's colour, at the midpoint of the side.
	 *
	 * Off the measured corners rather than off an idealised octagon, so the
	 * colours come back in the same order as the points they belong to — the
	 * rim is drawn as one segment per side, and a list that starts in the wrong
	 * place is a rim with its colours rotated.
	 *
	 * Pulled a tenth of the way toward the middle: the midpoint of a side sits
	 * exactly on the outline, where the pixels are half transparent, and a
	 * sample there comes back as a wash of the ring and whatever is behind it.
	 */
	const edges = corners.map(([ax, ay], i) => {
		const [bx, by] = corners[(i + 1) % corners.length];
		const mx = (ax + bx) / 2;
		const my = (ay + by) / 2;
		const p = at(mx + (cx - mx) * 0.1, my + (cy - my) * 0.1);
		return `#${[p.r, p.g, p.b].map((n) => n.toString(16).padStart(2, '0')).join('')}`;
	});

	/*
	 * The colour of the field between the middle and the ring — the mark's own
	 * dark ground. Sampled halfway out along eight directions and averaged, so
	 * one anti-aliased pixel cannot tint it.
	 */
	let fr = 0;
	let fg = 0;
	let fb = 0;
	for (let k = 0; k < 8; k++) {
		const angle = ((k + 0.5) / 8) * Math.PI * 2;
		const r = ((middle + 0.79) / 2) * cx;
		const p = at(cx + Math.cos(angle) * r, cy + Math.sin(angle) * r);
		fr += p.r;
		fg += p.g;
		fb += p.b;
	}
	const field = `#${[fr, fg, fb]
		.map((n) =>
			Math.round(n / 8)
				.toString(16)
				.padStart(2, '0')
		)
		.join('')}`;

	/*
	 * The ring's inner edge: the largest disc that is nothing but field.
	 *
	 * What the turning layer is cut to. `MARK_MIDDLE` used to stand in for
	 * this, on the reasoning that everything past the medallion is flat field
	 * anyway — true of a mark whose middle is a medallion, false of one whose
	 * middle is a drawing, where a disc cut just past the measured middle lands
	 * inside the artwork and turns a hole in it.
	 *
	 * Measured rather than assumed, and from the outside in: the answer is the
	 * biggest circle on which every sample is the field colour, so whatever the
	 * mark carries inside is whole within it and the cut itself falls where the
	 * drawing is the same at any angle.
	 */
	const isField = (p) =>
		p.a > 200 &&
		Math.abs(p.r - Math.round(fr / 8)) +
			Math.abs(p.g - Math.round(fg / 8)) +
			Math.abs(p.b - Math.round(fb / 8)) <=
			FIELD_TOLERANCE;

	/** Enough rays that a gap the width of the beak cannot slip between two. */
	const RAYS = 180;
	let inner = 0;
	for (let r = Math.round(cx) - 1; r > 1; r--) {
		let clear = true;
		for (let k = 0; k < RAYS; k++) {
			const angle = (k / RAYS) * Math.PI * 2;
			if (!isField(at(cx + Math.cos(angle) * r, cy + Math.sin(angle) * r))) {
				clear = false;
				break;
			}
		}
		if (clear) {
			inner = r / cx;
			break;
		}
	}

	return { middle: Number(middle.toFixed(4)), inner: Number(inner.toFixed(4)), edges, field };
}

if (polygon) {
	write(
		'src/lib/logo/mark-shape.ts',
		[
			`${'/'}**`,
			` * The mark's own outline, measured from \`mark.png\` by \`yarn icons\`.`,
			' *',
			' * Do not edit: replace the logo and run `yarn icons` instead. It is what lets',
			" * the phone bar's raised button be the shape of the mark rather than a circle",
			' * with the mark inside it.',
			' */',
			`export const MARK_CLIP_PATH =\n\t'polygon(${polygon})';`,
			'',
			`${'/'}**`,
			" * How much of the mark's half width its middle takes, and what colour each",
			' * side of its ring is.',
			' *',
			' * The section wheel is this drawing at two hundred and ninety pixels: the',
			" * ring is the wheel's rim, and the middle is the hole you let go in to",
			' * change your mind. Measured rather than typed, for the same reason the',
			' * outline is.',
			' */',
			`export const MARK_MIDDLE = ${parts ? parts.middle : 0.48};`,
			'',
			`export const MARK_EDGE_COLOURS = [\n${(parts?.edges ?? []).map((c) => `\t'${c}'`).join(',\n')}\n] as const;`,
			'',
			`${'/'}**`,
			' * The dark field between the middle and the ring — the ground the mark',
			" * carries inside itself. The phone bar wears it, so the mark's field",
			' * flows into the bar instead of ending at an edge.',
			' */',
			`export const MARK_FIELD = '${parts?.field ?? '#202830'}';`,
			'',
			`${'/'}**`,
			' * The same dark, lifted — what the mark wears where it stands for a copy',
			' * that is not the ordinary one.',
			' *',
			' * `MARK_FIELD_LIFT` in brand.ts is how far; this is the answer for this',
			' * artwork, so the app and the icons paint the same colour. Anywhere the',
			' * field is painted beside a drained mark wants this one instead.',
			' */',
			`export const MARK_FIELD_LIFTED = '${LIFTED_FIELD}';`,
			'',
			`${'/'}**`,
			" * Where the ring's inner edge is, as a fraction of the half width — the",
			' * largest disc inside the mark that is nothing but field.',
			' *',
			' * The layer that turns while the app waits is cut to it: everything the',
			' * mark carries inside is whole within this circle, and the circle itself',
			' * falls where the drawing is the same at any angle, so the cut cannot be',
			' * seen however far it has turned.',
			' */',
			`export const MARK_INNER = ${parts ? parts.inner : 0.78};`,
			''
		].join('\n')
	);
} else {
	console.log('  no rasteriser — src/lib/logo/mark-shape.ts left alone');
}

/* Last, because it reads constants declared alongside the helpers above and a
   call before those are initialised is a reference error, not a hoist. */
const hollow = hollowMark();
if (hollow) write('src/lib/logo/mark-hollow.png', hollow);
else console.log('  no pngjs — src/lib/logo/mark-hollow.png was left alone');

if (liftedPng) write('src/lib/logo/mark-lifted.png', liftedPng);
else console.log('  no pngjs — src/lib/logo/mark-lifted.png was left alone');

/* After everything, including the two derived rasters — the check used to run
   before them, so a stale `mark-hollow.png` on an otherwise clean tree passed. */
if (CHECK && stale) {
	console.error(`\n${stale} icon(s) out of date. Run: yarn icons`);
	process.exit(1);
}
console.log(stale ? `\n${stale} icon(s) redrawn.` : '\nEverything was already up to date.');
