/**
 * The docs, built from the code rather than written beside it.
 *
 * A hand-written page is true on the day it is written and quietly stops being
 * true afterwards, which is worse than no page at all because people trust it.
 * So every page here is derived from something the app actually enforces:
 *
 *   Data model     drizzle/meta/<latest>_snapshot.json — produced by
 *                  `yarn db:generate` from the schema, so it cannot disagree
 *                  with the tables that exist.
 *   HTTP API       the route files themselves, read as a syntax tree: the
 *                  methods they export and the scope each one demands, taken
 *                  from the `authenticateApi(event, '…')` call rather than
 *                  from a list somebody maintains.
 *   Scopes         the SCOPES object in services/tokens.ts.
 *   Services       each module's own header comment and its exported
 *                  signatures. The prose in this app already lives next to
 *                  the code and moves with it; this only collects it.
 *   Keyboard       PAGE_SHORTCUTS, the same table the app binds and the help
 *                  sheet renders.
 *
 * Anything that cannot be derived is not generated. A page that has to be
 * remembered is the thing this exists to avoid.
 *
 *   node scripts/build-docs.mjs           write docs/reference/
 *   node scripts/build-docs.mjs --check   fail if what is on disk is stale
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import * as prettier from 'prettier';

import { anchor } from './lib/anchor.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs', 'reference');
const CHECK = process.argv.includes('--check');

const STAMP = '<!-- Generated by scripts/build-docs.mjs. Do not edit: run `yarn docs`. -->\n\n';

/* ------------------------------------------------------------------ helpers */

function walk(dir, match, found = []) {
	if (!existsSync(dir)) return found;
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) walk(full, match, found);
		else if (match(entry.name)) found.push(full);
	}
	return found;
}

function parse(file) {
	return ts.createSourceFile(
		file,
		readFileSync(file, 'utf8'),
		ts.ScriptTarget.Latest,
		true,
		ts.ScriptKind.TS
	);
}

/** Strip the stars off a `/** … *\/` block and give back the prose inside. */
function undecorate(raw) {
	return raw
		.replace(/^\/\*\*/, '')
		.replace(/\*\/$/, '')
		.split('\n')
		.map((l) => l.replace(/^\s*\* ?/, '').trimEnd())
		.join('\n')
		.trim();
}

/**
 * The file's own header comment.
 *
 * By convention here it is the first `/** … *\/` in the file, which in most
 * modules sits *below* the imports — so it cannot be found by asking the first
 * statement what its leading comment is. Doing that attributed the header to
 * whichever declaration happened to follow it, and then handed that
 * declaration's own comment back as the module summary.
 */
function moduleDocOf(source) {
	const text = source.getFullText();

	/*
	 * At column zero, which is what makes it the file's rather than something
	 * else's. Without that, a route whose first `/** … *\/` happens to sit
	 * inside a function — a note on one field of a returned object, say — had
	 * that note published as the description of the whole page.
	 */
	let start = -1;
	for (let at = text.indexOf('/**'); at !== -1; at = text.indexOf('/**', at + 3)) {
		if (at === 0 || text[at - 1] === '\n') {
			start = at;
			break;
		}
	}
	if (start === -1) return '';

	const end = text.indexOf('*/', start);
	if (end === -1) return '';
	return undecorate(text.slice(start, end + 2));
}

/**
 * The comment block above a node, as prose.
 *
 * Only `/** … *\/` blocks: a `//` note is a remark to the next person editing
 * the line, and pulling those into a manual produces a page of asides. The
 * file header is excluded — it belongs to the module, and the statement that
 * happens to follow it must not claim it.
 */
function docOf(node, source, moduleDoc = '') {
	const ranges = ts.getLeadingCommentRanges(source.getFullText(), node.getFullStart()) ?? [];
	const blocks = ranges.filter((r) => source.getFullText().slice(r.pos, r.pos + 3) === '/**');
	if (!blocks.length) return '';

	const doc = undecorate(source.getFullText().slice(blocks.at(-1).pos, blocks.at(-1).end));
	return doc === moduleDoc ? '' : doc;
}

/** The first paragraph of a doc block — the sentence that says what a thing is. */
function summary(doc) {
	return doc.split('\n\n')[0].replace(/\n/g, ' ').trim();
}

/* -------------------------------------------------------------- data model */

function latestSnapshot() {
	const dir = join(ROOT, 'drizzle', 'meta');
	const snapshots = readdirSync(dir)
		.filter((f) => f.endsWith('_snapshot.json'))
		.sort();
	return JSON.parse(readFileSync(join(dir, snapshots.at(-1)), 'utf8'));
}

function dataModelPage() {
	const snapshot = latestSnapshot();
	const tables = Object.values(snapshot.tables).sort((a, b) => a.name.localeCompare(b.name));

	const out = [
		STAMP,
		'# Data model\n',
		`Every table the database has, from the migration snapshot \`drizzle-kit\` writes`,
		`out of the schema — so this page cannot disagree with the schema, and a`,
		`column added without a migration does not appear here because it does not`,
		`exist.\n`,
		`**${tables.length} tables.**\n`,
		'| Table | Columns | Belongs to a user |',
		'| --- | --- | --- |'
	];

	const ownsUser = (t) => Object.keys(t.columns).includes('user_id');
	for (const t of tables) {
		out.push(
			`| [\`${t.name}\`](#${anchor(t.name)}) | ${Object.keys(t.columns).length} | ${ownsUser(t) ? 'yes' : '—'} |`
		);
	}
	out.push('');

	for (const t of tables) {
		out.push(`## ${t.name}\n`);

		out.push('| Column | Type | Null | Default | Notes |');
		out.push('| --- | --- | --- | --- | --- |');

		const fks = Object.values(t.foreignKeys ?? {});
		for (const c of Object.values(t.columns)) {
			const notes = [];
			if (c.primaryKey) notes.push('primary key');
			if (c.autoincrement) notes.push('auto');
			const fk = fks.find((f) => (f.columnsFrom ?? []).includes(c.name));
			if (fk) notes.push(`→ \`${fk.tableTo}.${(fk.columnsTo ?? []).join(', ')}\``);

			out.push(
				`| \`${c.name}\` | ${c.type} | ${c.notNull ? 'not null' : 'null'} | ${
					c.default === undefined ? '—' : `\`${String(c.default)}\``
				} | ${notes.join(', ') || '—'} |`
			);
		}
		out.push('');

		const indexes = Object.values(t.indexes ?? {});
		if (indexes.length) {
			out.push('Indexes:\n');
			for (const i of indexes) {
				out.push(
					`- \`${i.name}\` on ${i.columns.map((c) => `\`${c}\``).join(', ')}${i.isUnique ? ' — unique' : ''}`
				);
			}
			out.push('');
		}

		const checks = Object.values(t.checkConstraints ?? {});
		if (checks.length) {
			out.push('Checks — enforced by the database, not only by the service layer:\n');
			for (const c of checks) out.push(`- \`${c.name}\`: \`${c.value}\``);
			out.push('');
		}
	}

	return out.join('\n');
}

/* -------------------------------------------------------------------- API */

/**
 * The scope a handler demands.
 *
 * Usually from its own `authenticateApi(event, 'scope')` call, which is the
 * one door nearly every endpoint goes through. The calendar feed is the
 * exception and has to be read differently: it authenticates the token itself,
 * because the credential is in the URL rather than in a header, and it demands
 * that the token hold *exactly* one scope. So a handler that names a known
 * scope as a string literal anywhere is taken at its word — otherwise the feed
 * appeared nowhere on this page and `calendar:read` looked like a scope no
 * endpoint had ever asked for.
 */
function scopeIn(node, source) {
	let scope = null;
	const known = new Set(scopeTable().map((r) => r.key));

	const visit = (n) => {
		if (
			ts.isCallExpression(n) &&
			n.expression.getText(source) === 'authenticateApi' &&
			n.arguments[1] &&
			ts.isStringLiteral(n.arguments[1])
		) {
			scope = n.arguments[1].text;
		}
		if (!scope && ts.isStringLiteral(n) && known.has(n.text)) scope = n.text;
		ts.forEachChild(n, visit);
	};
	visit(node);
	return scope;
}

function scopeTable() {
	const source = parse(join(ROOT, 'src/lib/server/services/tokens.ts'));
	const rows = [];

	const visit = (n) => {
		if (ts.isVariableDeclaration(n) && n.name.getText(source) === 'SCOPES' && n.initializer) {
			const obj = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;
			if (ts.isObjectLiteralExpression(obj)) {
				for (const prop of obj.properties) {
					if (!ts.isPropertyAssignment(prop)) continue;
					const key = prop.name.getText(source).replace(/['"]/g, '');
					const value = ts.isStringLiteral(prop.initializer) ? prop.initializer.text : '';
					rows.push({ key, value });
				}
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);
	return rows;
}

/** The SCOPE_CAUTIONS map, for the grants said louder. */
function cautionTable() {
	const source = parse(join(ROOT, 'src/lib/server/services/tokens.ts'));
	const rows = [];
	const visit = (n) => {
		if (
			ts.isVariableDeclaration(n) &&
			n.name.getText(source) === 'SCOPE_CAUTIONS' &&
			n.initializer
		) {
			const obj = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;
			if (ts.isObjectLiteralExpression(obj)) {
				for (const prop of obj.properties) {
					if (!ts.isPropertyAssignment(prop)) continue;
					const key = prop.name.getText(source).replace(/['"]/g, '');
					const value = ts.isStringLiteral(prop.initializer) ? prop.initializer.text : '';
					rows.push({ key, value });
				}
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);
	return rows;
}

/**
 * Every MCP tool, read from the array that serves them.
 *
 * The descriptions are the ones a model is handed, which is the point of
 * publishing them: what the docs promise and what an assistant is told are
 * the same strings.
 */
function mcpTools() {
	const source = parse(join(ROOT, 'src/lib/server/mcp/tools.ts'));
	const tools = [];
	const visit = (n) => {
		if (
			ts.isVariableDeclaration(n) &&
			n.name.getText(source) === 'TOOLS' &&
			n.initializer &&
			ts.isArrayLiteralExpression(n.initializer)
		) {
			for (const el of n.initializer.elements) {
				if (!ts.isObjectLiteralExpression(el)) continue;
				const tool = {};
				for (const prop of el.properties) {
					if (!ts.isPropertyAssignment(prop)) continue;
					const key = prop.name.getText(source);
					if (['name', 'title', 'description', 'scope'].includes(key)) {
						if (ts.isStringLiteral(prop.initializer)) tool[key] = prop.initializer.text;
					}
					if (key === 'writes') tool.writes = prop.initializer.kind === ts.SyntaxKind.TrueKeyword;
				}
				if (tool.name) tools.push(tool);
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);
	return tools;
}

function apiPage() {
	/*
	 * Every endpoint the app serves, not only the ones under `/api`.
	 *
	 * The calendar feed lives at `/calendar/[token]` because it is a URL people
	 * paste into a calendar app rather than something a plugin calls — and
	 * walking only `/api` meant this page did not know it existed, while the
	 * scope table above listed `calendar:read` as a permission nothing used.
	 */
	const files = walk(join(ROOT, 'src/routes'), (f) => f === '+server.ts');
	const endpoints = [];

	for (const file of files) {
		const source = parse(file);
		const urlPath =
			'/' + relative(join(ROOT, 'src/routes'), dirname(file)).split(/[\\/]/).join('/');

		const moduleDoc = moduleDocOf(source);

		const methods = [];
		for (const st of source.statements) {
			if (!ts.isVariableStatement(st)) continue;
			const isExported = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
			if (!isExported) continue;

			for (const decl of st.declarationList.declarations) {
				const name = decl.name.getText(source);
				if (!/^(GET|POST|PUT|PATCH|DELETE)$/.test(name)) continue;
				methods.push({
					method: name,
					scope: decl.initializer ? scopeIn(decl.initializer, source) : null,
					doc: docOf(st, source, moduleDoc)
				});
			}
		}

		if (methods.length) endpoints.push({ path: urlPath, moduleDoc, methods });
	}

	endpoints.sort((a, b) => a.path.localeCompare(b.path));

	const out = [
		STAMP,
		'# HTTP API\n',
		'Every endpoint the app answers on, read out of the route files',
		'themselves — the methods they export, and the scope each one demands.',
		'A handler that changes the scope it requires changes this page on the',
		'next build.\n',
		'## Scopes\n',
		'A token holds some of these and nothing else. Each description is the',
		'sentence somebody agrees to when they grant it.\n',
		'| Scope | What it permits |',
		'| --- | --- |'
	];
	for (const { key, value } of scopeTable()) out.push(`| \`${key}\` | ${value} |`);

	out.push('', '## Endpoints\n');
	out.push('| Endpoint | Method | Scope |');
	out.push('| --- | --- | --- |');
	for (const e of endpoints) {
		for (const m of e.methods) {
			out.push(`| \`${e.path}\` | ${m.method} | ${m.scope ? `\`${m.scope}\`` : '—'} |`);
		}
	}
	out.push('');

	const events = webhookEvents();
	if (events.length) {
		out.push('## Webhook events\n');
		out.push('What a subscription can ask to be told about. Managed through');
		out.push('`/settings/integrations` or the `webhooks:manage` scope.\n');
		out.push('| Event | Fires when |', '| --- | --- |');
		for (const e of events) out.push(`| \`${e.event}\` | ${e.label || '—'} |`);
		out.push('');
	}

	for (const e of endpoints) {
		out.push(`### \`${e.path}\`\n`);
		if (e.moduleDoc) out.push(e.moduleDoc + '\n');
		for (const m of e.methods) {
			out.push(`**${m.method}**${m.scope ? ` — requires \`${m.scope}\`` : ''}\n`);
			if (m.doc) out.push(m.doc + '\n');
		}
	}

	return out.join('\n');
}

/* --------------------------------------------------------------- services */

function servicesPage() {
	const dir = join(ROOT, 'src/lib/server/services');
	const files = readdirSync(dir)
		.filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
		.sort();

	const out = [
		STAMP,
		'# Services\n',
		'Every module in `src/lib/server/services`, with the comment it carries at',
		'the top and the functions it exports. All database access lives here:',
		'routes are adapters that read a form and call one of these, which is why',
		'this list is the closest thing the app has to a table of contents.\n',
		'Collected from the source, so a function renamed or a header rewritten',
		'shows up here on the next build.\n'
	];

	const modules = [];
	for (const file of files) {
		const source = parse(join(dir, file));
		const name = file.replace(/\.ts$/, '');

		const moduleDoc = moduleDocOf(source);

		const exports = [];
		for (const st of source.statements) {
			const isExported = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
			if (!isExported) continue;

			if (ts.isFunctionDeclaration(st) && st.name) {
				const params = st.parameters.map((p) => p.name.getText(source)).join(', ');
				exports.push({
					kind: 'function',
					signature: `${st.name.getText(source)}(${params})`,
					doc: docOf(st, source, moduleDoc)
				});
			} else if (ts.isVariableStatement(st)) {
				for (const decl of st.declarationList.declarations) {
					exports.push({
						kind: 'const',
						signature: decl.name.getText(source),
						doc: docOf(st, source, moduleDoc)
					});
				}
			} else if (ts.isTypeAliasDeclaration(st) || ts.isInterfaceDeclaration(st)) {
				exports.push({
					kind: 'type',
					signature: st.name.getText(source),
					doc: docOf(st, source, moduleDoc)
				});
			}
		}

		modules.push({ name, moduleDoc, exports });
	}

	out.push('| Module | What it is for |', '| --- | --- |');
	for (const m of modules) {
		out.push(`| [\`${m.name}\`](#${anchor(m.name)}) | ${summary(m.moduleDoc) || '—'} |`);
	}
	out.push('');

	for (const m of modules) {
		out.push(`## ${m.name}\n`);
		if (m.moduleDoc) out.push(m.moduleDoc + '\n');

		const fns = m.exports.filter((e) => e.kind === 'function');
		if (fns.length) {
			out.push('### Functions\n');
			for (const f of fns) {
				out.push(`#### \`${f.signature}\`\n`);
				if (f.doc) out.push(f.doc + '\n');
			}
		}

		const types = m.exports.filter((e) => e.kind === 'type');
		if (types.length) {
			out.push('### Types\n');
			for (const t of types) out.push(`- \`${t.signature}\`${t.doc ? ` — ${summary(t.doc)}` : ''}`);
			out.push('');
		}
	}

	return out.join('\n');
}

/* -------------------------------------------------------------- shortcuts */

/**
 * The tree: which rooms the app has, and what is inside each.
 *
 * Read from the two places that decide it — `NAV_PLACES` for the rooms and
 * each section's own `+layout.svelte` for its tabs — because a hand-written
 * map of the interface is a map that is wrong within a month. A room whose
 * layout has no tab strip is a single page and says so.
 */
function interfacesPage() {
	const source = parse(join(ROOT, 'src/lib/sections-nav.ts'));

	/** The rooms, in the order the navigation bar shows them. */
	const rooms = [];
	const visitNav = (node) => {
		if (
			ts.isVariableDeclaration(node) &&
			node.name.getText(source) === 'NAV_PLACES' &&
			node.initializer &&
			ts.isArrayLiteralExpression(node.initializer)
		) {
			for (const el of node.initializer.elements) {
				if (!ts.isObjectLiteralExpression(el)) continue;
				const read = (key) => {
					const prop = el.properties.find(
						(pr) => ts.isPropertyAssignment(pr) && pr.name.getText(source) === key
					);
					return prop && ts.isStringLiteral(prop.initializer) ? prop.initializer.text : '';
				};
				rooms.push({
					key: read('key'),
					label: read('label'),
					href: read('href'),
					hide: read('hide')
				});
			}
		}
		ts.forEachChild(node, visitNav);
	};
	visitNav(source);

	/** A section's tabs, in the order its layout lists them. */
	const tabsOf = (dir) => {
		const file = join(ROOT, `src/routes/${dir}/+layout.svelte`);
		if (!existsSync(file)) return [];
		const text = readFileSync(file, 'utf8');
		const out = [];
		// `resolve('/health/recipes'), label: 'Recipes'` — the shape every tab
		// strip uses. A tab built from data (a data stream's own tab) has no
		// literal to read and is described in prose below instead.
		const re = /resolve\((?:'|`)([^'`]+)(?:'|`)[^)]*\)[^}]*?label:\s*'([^']+)'/g;
		let m;
		while ((m = re.exec(text)) !== null) out.push({ href: m[1], label: m[2] });
		return out;
	};

	const lines = [
		STAMP.trimEnd(),
		'',
		'# Interfaces',
		'',
		'Every room the app has, and what is inside it. Generated from the',
		'navigation and from each section\u2019s own tab strip, so it cannot drift',
		'from what the app actually shows.',
		''
	];

	for (const room of rooms) {
		const dir = room.href.split('/')[1];
		const tabs = tabsOf(dir);
		lines.push(`### ${room.label}`);
		lines.push('');
		if (tabs.length > 0) {
			for (const tab of tabs) lines.push(`- **${tab.label}** — \`${tab.href}\``);
		} else {
			lines.push(`- \`${room.href}\` — one page, no tabs`);
		}
		if (room.hide) {
			lines.push('');
			lines.push(
				`Can be put away in Preferences (\`${room.hide}\`), which takes it out of the bar, the wheel and the dashboard.`
			);
		}
		lines.push('');
	}

	lines.push('### Everywhere else');
	lines.push('');
	lines.push('- **Home** — `/`, the dashboard; the wordmark is the way back to it');
	lines.push('- **Search** — `/search`, across every room at once');
	lines.push('- **Settings** — `/settings`, and the account under it');
	lines.push(
		'- Health also grows a tab per data stream an account records, named after the stream.'
	);
	lines.push('');

	return lines.join('\n');
}

function shortcutsPage() {
	const source = parse(join(ROOT, 'src/lib/shortcuts.ts'));
	const global = [];
	const pages = [];

	const readBindings = (arr) =>
		arr.elements.filter(ts.isObjectLiteralExpression).map((el) => {
			const get = (key) => {
				const p = el.properties.find(
					(pr) => ts.isPropertyAssignment(pr) && pr.name.getText(source) === key
				);
				return p && ts.isStringLiteral(p.initializer) ? p.initializer.text : '';
			};
			return { key: get('key'), action: get('action'), description: get('description') };
		});

	const visit = (n) => {
		if (ts.isVariableDeclaration(n) && n.initializer) {
			const name = n.name.getText(source);
			if (name === 'GLOBAL_SHORTCUTS' && ts.isArrayLiteralExpression(n.initializer)) {
				global.push(...readBindings(n.initializer));
			}
			if (name === 'PAGE_SHORTCUTS') {
				const obj = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;
				if (ts.isObjectLiteralExpression(obj)) {
					for (const prop of obj.properties) {
						if (!ts.isPropertyAssignment(prop)) continue;
						const path = prop.name.getText(source).replace(/['"]/g, '');
						const value = prop.initializer;
						if (!ts.isObjectLiteralExpression(value)) continue;

						const labelProp = value.properties.find(
							(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === 'label'
						);
						const listProp = value.properties.find(
							(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === 'shortcuts'
						);

						pages.push({
							path,
							label:
								labelProp && ts.isStringLiteral(labelProp.initializer)
									? labelProp.initializer.text
									: path,
							shortcuts:
								listProp && ts.isArrayLiteralExpression(listProp.initializer)
									? readBindings(listProp.initializer)
									: []
						});
					}
				}
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);

	const out = [
		STAMP,
		'# Keyboard\n',
		'The same table the app binds and the `?` sheet renders, so a key that',
		'works is a key listed here and the reverse.\n',
		'## Everywhere\n',
		'| Key | Does |',
		'| --- | --- |'
	];
	for (const s of global) out.push(`| <kbd>${s.key}</kbd> | ${s.description} |`);
	out.push('');

	for (const p of pages.sort((a, b) => a.path.localeCompare(b.path))) {
		out.push(`## ${p.label} — \`${p.path}\`\n`);
		out.push('| Key | Does |', '| --- | --- |');
		for (const s of p.shortcuts) out.push(`| <kbd>${s.key}</kbd> | ${s.description} |`);
		out.push('');
	}

	return out.join('\n');
}

/* ------------------------------------------------------------------ tutorials */

/**
 * The tours, and the screens still waiting for one.
 *
 * Read out of `src/lib/tutorials.ts`, `src/lib/sections-nav.ts` and
 * `src/lib/shortcuts.ts` rather than listed anywhere: a room added to the
 * navigation is a room this page immediately reports as untoured, which is the
 * only arrangement in which "we forgot to write the tutorial" is a thing
 * somebody finds out before a stranger does.
 */
function tutorialsPage() {
	/** path → { label, steps: [title] } */
	const tours = new Map();
	{
		const source = parse(join(ROOT, 'src/lib/tutorials.ts'));
		const visit = (n) => {
			if (
				ts.isVariableDeclaration(n) &&
				n.name.getText(source) === 'TUTORIALS' &&
				n.initializer &&
				ts.isObjectLiteralExpression(n.initializer)
			) {
				for (const prop of n.initializer.properties) {
					if (!ts.isPropertyAssignment(prop) || !ts.isObjectLiteralExpression(prop.initializer))
						continue;
					const path = prop.name.getText(source).replace(/['"]/g, '');
					const at = (key) =>
						prop.initializer.properties.find(
							(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === key
						);
					const labelProp = at('label');
					const stepsProp = at('steps');
					const steps =
						stepsProp && ts.isArrayLiteralExpression(stepsProp.initializer)
							? stepsProp.initializer.elements.filter(ts.isObjectLiteralExpression).map((el) => {
									const title = el.properties.find(
										(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === 'title'
									);
									return title && ts.isStringLiteral(title.initializer)
										? title.initializer.text
										: '';
								})
							: [];
					tours.set(path, {
						label:
							labelProp && ts.isStringLiteral(labelProp.initializer)
								? labelProp.initializer.text
								: path,
						steps
					});
				}
			}
			ts.forEachChild(n, visit);
		};
		visit(source);
	}

	// Somewhere the navigation goes, or somewhere with keys of its own: either
	// is a screen somebody arrives at without having been told what it is.
	const owed = new Set();
	{
		const source = parse(join(ROOT, 'src/lib/sections-nav.ts'));
		const visit = (n) => {
			if (
				ts.isVariableDeclaration(n) &&
				n.name.getText(source) === 'NAV_PLACES' &&
				n.initializer &&
				ts.isArrayLiteralExpression(n.initializer)
			) {
				for (const el of n.initializer.elements) {
					if (!ts.isObjectLiteralExpression(el)) continue;
					const href = el.properties.find(
						(p) => ts.isPropertyAssignment(p) && p.name.getText(source) === 'href'
					);
					if (href && ts.isStringLiteral(href.initializer)) owed.add(href.initializer.text);
				}
			}
			ts.forEachChild(n, visit);
		};
		visit(source);
	}
	{
		const source = parse(join(ROOT, 'src/lib/shortcuts.ts'));
		const visit = (n) => {
			if (
				ts.isVariableDeclaration(n) &&
				n.name.getText(source) === 'PAGE_SHORTCUTS' &&
				n.initializer
			) {
				const obj = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;
				if (ts.isObjectLiteralExpression(obj)) {
					for (const prop of obj.properties) {
						if (!ts.isPropertyAssignment(prop)) continue;
						owed.add(prop.name.getText(source).replace(/['"]/g, ''));
					}
				}
			}
			ts.forEachChild(n, visit);
		};
		visit(source);
	}

	const screens = [...owed].sort();
	const covered = screens.filter((s) => tours.has(s));
	const extra = [...tours.keys()].filter((p) => !owed.has(p)).sort();

	const out = [
		STAMP,
		'# Tutorials\n',
		'The guided tours: the screen dims and one thing at a time does not. Shown',
		'once on a new account and on every visit to the demo, and on the `?` button',
		'in the corner of every screen afterwards.\n',
		'This page is the coverage. A room added to the navigation, or a page given',
		'keyboard shortcuts, is a screen owed a tour — and turns up here as **none**',
		'until somebody writes one in `src/lib/tutorials.ts`. The same gap is visible',
		'in the app: the `?` button goes red on a screen with no tour and says so',
		'under the pointer.\n',
		`**${covered.length} of ${screens.length} screens have one.**\n`,
		'| Screen | Tour | Steps |',
		'| --- | --- | --- |'
	];

	for (const screen of screens) {
		const tour = tours.get(screen);
		out.push(
			`| \`${screen}\` | ${tour ? tour.label : '**none**'} | ${tour ? tour.steps.length : '—'} |`
		);
	}
	out.push('');

	if (extra.length) {
		out.push(
			'Toured as well, though nothing obliges them to be — a screen reached from',
			'a link rather than from the navigation:\n'
		);
		for (const path of extra) out.push(`- \`${path}\` — ${tours.get(path).label}`);
		out.push('');
	}

	out.push('## What each one says\n');
	out.push(
		'The steps, in order. Every tour ends on the same closing step, which points',
		'at the button that reopens it, so it is not listed here.\n'
	);
	for (const path of [...tours.keys()].sort()) {
		const tour = tours.get(path);
		out.push(`### \`${path}\` — ${tour.label}\n`);
		tour.steps.forEach((title, i) => out.push(`${i + 1}. ${title}`));
		out.push('');
	}

	return out.join('\n');
}

/* ------------------------------------------------------------- pages/actions */

/**
 * Turn a route directory into the URL it answers on.
 *
 * SvelteKit's grouping folders — `(app)`, `(marketing)` — organise the source
 * and are not part of any address, so they come out. `[id]` stays, because a
 * parameter is part of the shape of the URL even though it is not part of any
 * one address.
 */
function urlFor(dir) {
	const rel = relative(join(ROOT, 'src/routes'), dir).split(/[\\/]/).filter(Boolean);
	const parts = rel.filter((p) => !/^\(.*\)$/.test(p));
	return '/' + parts.join('/');
}

function pagesPage() {
	const serverFiles = walk(join(ROOT, 'src/routes'), (f) => f === '+page.server.ts');
	const pageFiles = walk(join(ROOT, 'src/routes'), (f) => f === '+page.svelte');

	const byUrl = new Map();
	const touch = (url) => {
		if (!byUrl.has(url)) byUrl.set(url, { url, actions: [], hasPage: false, doc: '' });
		return byUrl.get(url);
	};

	for (const file of pageFiles) touch(urlFor(dirname(file))).hasPage = true;

	for (const file of serverFiles) {
		const source = parse(file);
		const entry = touch(urlFor(dirname(file)));
		const moduleDoc = moduleDocOf(source);
		// The prose a route already carries at the top of its own file. Written
		// beside the code it describes, so it moves with it — which is the only
		// arrangement in which it stays true.
		entry.doc = moduleDoc;

		for (const st of source.statements) {
			if (!ts.isVariableStatement(st)) continue;
			const isExported = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
			if (!isExported) continue;

			for (const decl of st.declarationList.declarations) {
				if (decl.name.getText(source) !== 'actions' || !decl.initializer) continue;

				const obj = ts.isSatisfiesExpression(decl.initializer)
					? decl.initializer.expression
					: decl.initializer;
				if (!ts.isObjectLiteralExpression(obj)) continue;

				for (const prop of obj.properties) {
					if (!prop.name) continue;
					entry.actions.push({
						name: prop.name.getText(source).replace(/['"]/g, ''),
						doc: docOf(prop, source, moduleDoc)
					});
				}
			}
		}
	}

	const routes = [...byUrl.values()]
		.filter((r) => r.hasPage || r.actions.length)
		.sort((a, b) => a.url.localeCompare(b.url));

	const totalActions = routes.reduce((n, r) => n + r.actions.length, 0);

	const out = [
		STAMP,
		'# Pages and actions\n',
		'Every address the app serves a page on, and every form action behind it —',
		'read from the route tree, so a page added or an action renamed shows up',
		'here on the next build.\n',
		'An action is what a `<form method="post">` posts to. They are the app\'s',
		'own write surface, the way the endpoints in [the API](api.md) are the',
		'write surface for everything else; both end up calling the same',
		'[services](services.md).\n',
		`**${routes.length} pages, ${totalActions} actions.**\n`,
		'| Page | Actions |',
		'| --- | --- |'
	];

	for (const r of routes) {
		out.push(
			`| \`${r.url}\` | ${
				r.actions.length ? r.actions.map((a) => `\`${a.name}\``).join(', ') : '—'
			} |`
		);
	}
	out.push('');

	const documented = routes.filter((r) => r.doc || r.actions.some((a) => a.doc));
	if (documented.length) {
		out.push('## What these pages do\n');
		out.push(
			'Only the ones whose code says — the comment at the top of the route file,',
			'and the comment above each action. Write it there and it turns up here;',
			'the rest are named for what they do.\n'
		);
		for (const r of documented) {
			out.push(`### \`${r.url}\`\n`);
			if (r.doc) out.push(r.doc + '\n');
			for (const a of r.actions.filter((a) => a.doc)) {
				out.push(`**\`${a.name}\`**\n`);
				out.push(a.doc + '\n');
			}
		}
	}

	return out.join('\n');
}

/* ---------------------------------------------------------------- config */

/**
 * Every `ONTOPLANO_*` variable the source actually reads.
 *
 * Two patterns, because there are two ways the code reads one. Most places name
 * it outright — `process.env.ONTOPLANO_DEMO` — and the first expression catches
 * those. But `settings.ts` reads its numbers through helpers (`int('ONTOPLANO_
 * PRICE_MONTHLY_CENTS', …)`, `flag('ONTOPLANO_FAMILY_PLAN')`), and a scanner
 * that only looked for the literal member access silently omitted the whole
 * pricing block — which is exactly the drift this table exists to prevent. So
 * the second expression takes any `ONTOPLANO_*` written as a string literal.
 */
function environmentVariables() {
	const files = [
		...walk(join(ROOT, 'src'), (f) => f.endsWith('.ts')),
		...walk(join(ROOT, 'scripts'), (f) => f.endsWith('.mjs') || f.endsWith('.ts'))
	];

	const patterns = [/process\.env\.(ONTOPLANO_[A-Z0-9_]+)/g, /['"`](ONTOPLANO_[A-Z0-9_]+)['"`]/g];

	const found = new Map();
	for (const file of files) {
		// Not this file: the comment above names two variables as examples, and a
		// scanner that reads itself would list itself as their reader.
		if (file.includes('.test.') || file.endsWith('build-docs.mjs')) continue;
		const text = readFileSync(file, 'utf8');
		const where = relative(ROOT, file);
		for (const pattern of patterns) {
			for (const m of text.matchAll(pattern)) {
				if (!found.has(m[1])) found.set(m[1], new Set());
				found.get(m[1]).add(where);
			}
		}
	}

	return [...found.entries()].sort(([a], [b]) => a.localeCompare(b));
}

/** The shape of config.toml, from the interface that types it. */
function configShape() {
	const source = parse(join(ROOT, 'src/lib/server/config.ts'));
	const sections = [];

	const visit = (n) => {
		if (ts.isInterfaceDeclaration(n) && n.name.getText(source) === 'OntoplanoConfig') {
			for (const member of n.members) {
				if (!ts.isPropertySignature(member) || !member.type) continue;
				const section = member.name.getText(source);
				const keys = [];

				if (ts.isTypeLiteralNode(member.type)) {
					for (const sub of member.type.members) {
						if (!ts.isPropertySignature(sub) || !sub.type) continue;
						keys.push({
							name: sub.name.getText(source),
							type: sub.type.getText(source),
							doc: docOf(sub, source)
						});
					}
				}
				sections.push({ section, keys });
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);
	return sections;
}

/** The per-account settings keys, from the constants that name them. */
function userSettingKeys() {
	const source = parse(join(ROOT, 'src/lib/server/settings.ts'));
	const keys = [];

	const visit = (n) => {
		if (
			ts.isVariableDeclaration(n) &&
			/_KEY$/.test(n.name.getText(source)) &&
			n.initializer &&
			ts.isStringLiteral(n.initializer)
		) {
			keys.push({ constant: n.name.getText(source), key: n.initializer.text });
		}
		ts.forEachChild(n, visit);
	};
	visit(source);
	return keys.sort((a, b) => a.key.localeCompare(b.key));
}

function configurationPage() {
	const out = [
		STAMP,
		'# Configuration\n',
		'Three separate things, often confused: what the **operator** sets for the',
		'whole instance, what the **process** is told through its environment, and',
		'what each **account** chooses for itself.\n',
		'## config.toml\n',
		'Written to `~/.config/ontoplano/config.toml` on first run, and edited by',
		'the operator or through `/admin`. Its shape is the `OntoplanoConfig`',
		'interface, so this table is that interface.\n'
	];

	for (const { section, keys } of configShape()) {
		out.push(`### \`[${section}]\`\n`);
		out.push('| Key | Type | Means |', '| --- | --- | --- |');
		for (const k of keys) {
			out.push(`| \`${k.name}\` | \`${k.type}\` | ${summary(k.doc) || '—'} |`);
		}
		out.push('');
		for (const k of keys.filter((k) => k.doc && k.doc !== summary(k.doc))) {
			out.push(`**\`${k.name}\`**\n`, k.doc + '\n');
		}
	}

	out.push('## Environment\n');
	out.push('Every `ONTOPLANO_*` variable the code actually reads, and where it is');
	out.push('read. A variable that stops being consulted leaves this table by');
	out.push('itself, which is the point — an env var nobody reads any more is the');
	out.push('kind of thing that stays in a deployment script for years.\n');
	out.push('| Variable | Read in |', '| --- | --- |');
	for (const [name, where] of environmentVariables()) {
		out.push(
			`| \`${name}\` | ${[...where]
				.sort()
				.map((w) => `\`${w}\``)
				.join(', ')} |`
		);
	}
	out.push('');

	out.push('## Per-account settings\n');
	out.push('Rows in `user_settings`, one per account per key. These are choices a');
	out.push('person makes about their own copy of the app, not the operator.\n');
	out.push('| Key | Constant |', '| --- | --- |');
	for (const k of userSettingKeys()) out.push(`| \`${k.key}\` | \`${k.constant}\` |`);

	return out.join('\n');
}

/* -------------------------------------------------------------- webhooks */

function webhookEvents() {
	const source = parse(join(ROOT, 'src/lib/server/services/webhooks.ts'));
	const labels = new Map();
	const events = [];

	const visit = (n) => {
		if (ts.isVariableDeclaration(n) && n.initializer) {
			const name = n.name.getText(source);
			const init = ts.isAsExpression(n.initializer) ? n.initializer.expression : n.initializer;

			if (name === 'WEBHOOK_EVENTS' && ts.isArrayLiteralExpression(init)) {
				for (const el of init.elements) {
					if (ts.isStringLiteral(el)) events.push(el.text);
				}
			}
			if (name === 'WEBHOOK_EVENT_LABELS' && ts.isObjectLiteralExpression(init)) {
				for (const prop of init.properties) {
					if (!ts.isPropertyAssignment(prop)) continue;
					const key = prop.name.getText(source).replace(/['"]/g, '');
					if (ts.isStringLiteral(prop.initializer)) labels.set(key, prop.initializer.text);
				}
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(source);

	return events.map((e) => ({ event: e, label: labels.get(e) ?? '' }));
}

/* ------------------------------------------------------------------ prose */

/**
 * The half of the docs a generator cannot write.
 *
 * Everything else here is derived, which is what stops it going stale — but
 * "the migration snapshot says `todo_tasks.scheduled_date` is nullable" is
 * not an explanation of what a todo *is*, and no amount of reading the schema
 * produces one. So prose lives in `docs/prose/`, is edited by hand, and is
 * built into the docs beside the generated pages.
 *
 * What keeps it from going stale in its own way is that the parts which *can*
 * be derived are not written down twice: a line reading
 *
 *     <!-- generated: scopes -->
 *
 * is replaced with the current table on every build. The prose says why the
 * thing exists; the generator says what it currently is.
 *
 * A page declares its own title and blurb for the index in the same shape:
 *
 *     <!-- title: The plan -->
 *     <!-- blurb: what a block, an occurrence and a todo each are -->
 */
const PROSE_DIR = join(ROOT, 'docs', 'prose');

const PROSE_STAMP =
	'<!-- Written by hand in docs/prose/%s — edit that file, then run `yarn docs`.\n' +
	'     The tables below marked "generated" come from the code itself. -->\n\n';

/** The blocks a prose page may ask for, by name. */
const FRAGMENTS = {
	scopes: () =>
		[
			'| Scope | What granting it allows |',
			'| --- | --- |',
			...scopeTable().map((r) => `| \`${r.key}\` | ${r.value} |`)
		].join('\n'),
	'mcp-tools': () => {
		const tools = mcpTools();
		return tools
			.map(
				(t) =>
					`### \`${t.name}\` — ${t.title}\n\n${t.description}\n\n_Needs \`${t.scope}\`; ${t.writes ? 'writes' : 'read-only'}._`
			)
			.join('\n\n');
	},
	permissions: () => {
		const uses = new Map();
		for (const t of mcpTools()) {
			if (!uses.has(t.scope)) uses.set(t.scope, []);
			uses.get(t.scope).push(t.name);
		}
		const cautions = new Map(cautionTable().map((r) => [r.key, r.value]));
		return [
			'| Scope | What granting it allows | MCP tools behind it |',
			'| --- | --- | --- |',
			...scopeTable().map((r) => {
				const said = cautions.has(r.key)
					? `${r.value}.<br>**Careful:** ${cautions.get(r.key)}`
					: r.value;
				const tools = (uses.get(r.key) ?? []).map((n) => `\`${n}\``).join(', ') || '—';
				return `| \`${r.key}\` | ${said} | ${tools} |`;
			})
		].join('\n');
	},
	'webhook-events': () =>
		[
			'| Event | When it fires |',
			'| --- | --- |',
			...webhookEvents().map((e) => `| \`${e.event}\` | ${e.label} |`)
		].join('\n')
};

function prosePages() {
	if (!existsSync(PROSE_DIR)) return [];

	return readdirSync(PROSE_DIR)
		.filter((f) => f.endsWith('.md'))
		.sort()
		.map((file) => {
			const raw = readFileSync(join(PROSE_DIR, file), 'utf8');
			const title = /<!--\s*title:\s*(.+?)\s*-->/.exec(raw)?.[1];
			const blurb = /<!--\s*blurb:\s*(.+?)\s*-->/.exec(raw)?.[1];
			if (!title || !blurb) {
				console.error(`${file}: needs a <!-- title: … --> and a <!-- blurb: … --> line`);
				process.exit(1);
			}

			const body = raw
				.replace(/<!--\s*(?:title|blurb):.*?-->\n?/g, '')
				.replace(/^[^\S\n]*<!--\s*generated:\s*([\w-]+)\s*-->[^\S\n]*$/gm, (line, name) => {
					const fragment = FRAGMENTS[name];
					if (!fragment) {
						console.error(`${file}: no generated block called "${name}"`);
						process.exit(1);
					}
					return fragment();
				});

			return {
				file,
				title,
				blurb,
				build: () => PROSE_STAMP.replace('%s', file) + body.trimStart()
			};
		});
}

/* ------------------------------------------------------------------ index */

function indexPage(pages, written) {
	return [
		STAMP,
		'# How ontoplano works\n',
		'Most of these pages are built rather than written. The reference pages are',
		'generated by `scripts/build-docs.mjs` from something the running app',
		'enforces — the migration snapshot, the route files, the scope table, the',
		'shortcut map — so a change to the logic changes the page on the next',
		'build, and a page cannot quietly stop being true.\n',
		'Run `yarn docs` to rebuild. `yarn docs:check` fails if what is committed',
		'is out of date, which is what keeps the two honest.\n',
		'## What the app is\n',
		'How the pieces fit, and why. The tables inside are generated.\n',
		...written.map((p) => `- [${p.title}](${p.file}) — ${p.blurb}`),
		'',
		'## Reference\n',
		'Generated from the code, on every build.\n',
		...pages.map((p) => `- [${p.title}](${p.file}) — ${p.blurb}`),
		'',
		'## What is not here\n',
		'The reasoning behind a particular line lives in the comment above that',
		'line, where it moves with the code — these pages collect those rather than',
		'restating them. The guides for running an instance — Docker, backups, plans,',
		'plugins, the Android build — are in `docs/` beside this directory, because',
		'they describe things outside this repository that no generator can read.'
	].join('\n');
}

/* ------------------------------------------------------------------- main */

const PAGES = [
	{
		file: 'data-model.md',
		title: 'Data model',
		blurb: 'every table and column, from the migration snapshot',
		build: dataModelPage
	},
	{
		file: 'api.md',
		title: 'HTTP API',
		blurb: 'endpoints and the scope each one demands',
		build: apiPage
	},
	{
		file: 'services.md',
		title: 'Services',
		blurb: 'the service layer, module by module',
		build: servicesPage
	},
	{
		file: 'interfaces.md',
		title: 'Interfaces',
		blurb: 'the rooms, and what is inside each',
		build: interfacesPage
	},
	{
		file: 'pages.md',
		title: 'Pages and actions',
		blurb: 'every address, and the form actions behind it',
		build: pagesPage
	},
	{
		file: 'configuration.md',
		title: 'Configuration',
		blurb: 'config.toml, the environment, and per-account settings',
		build: configurationPage
	},
	{
		file: 'keyboard.md',
		title: 'Keyboard',
		blurb: 'every shortcut, per page',
		build: shortcutsPage
	},
	{
		file: 'tutorials.md',
		title: 'Tutorials',
		blurb: 'the guided tours, and the screens still without one',
		build: tutorialsPage
	}
];

/*
 * Formatted by prettier on the way out.
 *
 * The repo checks every file with prettier, so a generator that emits markdown
 * prettier would rewrite gives you two commands that disagree about the same
 * file forever — `yarn docs` writes it, `yarn lint` rejects it. Running its
 * output through the same formatter the repo uses settles that at the source.
 */
const config = (await prettier.resolveConfig(join(ROOT, 'docs/reference/README.md'))) ?? {};
const format = (text) => prettier.format(text, { ...config, parser: 'markdown' });

const WRITTEN = prosePages();

const built = new Map();
for (const page of [...WRITTEN, ...PAGES]) built.set(page.file, await format(page.build()));
built.set('README.md', await format(indexPage(PAGES, WRITTEN)));

if (CHECK) {
	const stale = [];
	for (const [file, content] of built) {
		const path = join(OUT, file);
		if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(file);
	}
	// Something committed that the generator no longer produces is drift too.
	const extra = existsSync(OUT)
		? readdirSync(OUT).filter((f) => f.endsWith('.md') && !built.has(f))
		: [];

	if (stale.length || extra.length) {
		console.error('The docs is out of date. Run `yarn docs` and commit the result.\n');
		for (const f of stale) console.error(`  stale:   docs/reference/${f}`);
		for (const f of extra) console.error(`  orphan:  docs/reference/${f}`);
		process.exit(1);
	}
	console.log(`docs: ${built.size} pages up to date`);
} else {
	rmSync(OUT, { recursive: true, force: true });
	mkdirSync(OUT, { recursive: true });
	for (const [file, content] of built) writeFileSync(join(OUT, file), content);
	console.log(`docs: wrote ${built.size} pages to docs/reference/`);
}
